-- ============================================
-- Day 12: Subqueries Part 2 & CTEs - CRAZY HARD Level
-- Student Question Bank (100 Questions)
-- ============================================
-- Topics Covered: Correlated Subqueries, ANY/SOME/ALL, CTEs (WITH clause), Multiple CTEs, Recursive CTEs
-- 
-- Concepts ALLOWED:
--   - All concepts from Days 1-11 (SELECT, WHERE, JOINs, Aggregates, CASE, Basic Subqueries, Set Operations)
--   - Correlated subqueries
--   - ANY, SOME, ALL operators
--   - WITH clause (Common Table Expressions)
--   - Multiple CTEs in single query
--   - Recursive CTEs (base case + recursive case)
--   - Hierarchical queries
--
-- Concepts NOT ALLOWED:
--   - Window Functions (ROW_NUMBER, RANK, DENSE_RANK, LEAD, LAG, etc.)
--   - OVER clause, PARTITION BY
--   - Transactions, Views, Functions, Procedures
-- ============================================

-- Q1. During the chaotic aftermath of Flipkart's Big Billion Day sale, the finance director stormed into the analytics pit at 2 AM demanding answers. "Our revenue numbers don't match between the orders table and payments table," she fumed, "and I need to present to the board in 6 hours. Find me every order where payment received differs from order amount by more than ₹100, but only for orders that were placed by customers who had previously complained about billing issues - which I'm told we can identify as customers who have returned something with reason containing 'billing' or 'charge'. Oh, and sort this by the magnitude of discrepancy, largest first. Also give me the total discrepancy amount if we were to refund all these customers."

-- Q2. BigBasket's new VP of Supply Chain arrived from Amazon with grand ideas about "inventory velocity optimization." In his first week, he scheduled a meeting titled "Finding the Bleeding Heart of Our Warehouse" and asked the data team to identify what he calls "zombie inventory" - products that haven't moved in 90 days, currently have stock above 50 units, were ordered at least once in the company's history (so we know they can sell), but here's the kicker - they should have sold based on their historical daily run rate but mysteriously stopped. Calculate what their expected sales should have been over these 90 days based on their pre-dormancy average daily sales, and show the "ghost revenue" we're missing. The VP wants to see this broken down by category, sorted by total ghost revenue in descending order.

-- Q3. Zomato's customer success team lead, Priya, has been tracking something she calls the "silent churner" phenomenon - customers who don't officially leave but slowly fade away. She defines a silent churner as someone who: (a) was once in the top 30% of spenders based on their first 6 months, (b) hasn't ordered in the last 45 days, (c) their last order value was less than 40% of their personal average order value, (d) they received at least 3 marketing emails in the past month but didn't click any, and (e) - this is the tricky part - their "engagement decay rate" (number of orders in most recent quarter divided by orders in the quarter before that) is less than 0.5. Priya needs the list sorted by their historical total spending, with a flag indicating if they've ever given a 5-star review (potential brand advocates worth saving).

-- Q4. Amazon India's marketplace integrity team has been battling a sophisticated fraud ring they've dubbed "The Phoenix Scheme." The fraudsters create new accounts, make one legitimate purchase to build history, then immediately return it for refund while simultaneously placing large orders with stolen credit cards. The pattern they've identified is: customers who (a) joined within the last 90 days, (b) their first order was under ₹500, (c) that first order was returned, (d) they subsequently placed an order exceeding ₹10,000 within 7 days of the return, (e) the payment mode for the large order differs from their first order, and (f) they haven't placed any order since that large order. Build a fraud detection query that scores each suspect based on how many of these criteria they match, showing all customers matching at least 4 of the 6 criteria.

-- Q5. Paytm Mall's regional expansion head is planning the next phase of warehouse investments. She has a complex optimization problem: identify cities where (a) current average delivery time exceeds 4 days, (b) total order value in the past year exceeded ₹50 lakhs, (c) the city has at least 500 unique customers, (d) but here's the nuance - the city's customer growth rate (new customers this quarter vs last quarter) must be higher than the national average growth rate, AND (e) the city must not already have a fulfillment center (no stores in that city), AND (f) the average order value in that city should be within 20% of the national average (we don't want outlier cities skewing our planning). Rank these cities by a composite score of (delivery time gap × order volume × customer growth rate).

-- Q6. Myntra's merchandising team discovered what they call the "cannibalization cascade" - when a new product launch kills sales of existing products, which then affects other products in a chain reaction. They need to trace products where: (a) they were launched (first ordered) in the past 6 months, (b) within 30 days of their launch, at least 2 other products in the same category experienced sales decline of more than 30% compared to the 30 days before the launch, (c) these affected products were from the same brand OR were in the same price bracket (within ₹200), (d) the new product's total sales in its first 60 days exceeded the combined lost sales of the affected products (making it a "net positive" launch). Show the cannibalizer products, their "victims," the sales delta, and the net impact to the category.

-- Q7. Reliance Retail's HR analytics team is investigating what they suspect is a "glass ceiling" effect in their organization. They need to build an equity analysis that identifies: employees who have been with the company for more than 3 years (based on earliest salary_history record), whose current salary is still below the average entry salary of employees who joined within the last year in the same department, AND whose salary growth rate (latest salary / first salary) is lower than the department average growth rate, AND who have never had a salary increase that exceeded 20% year-over-year. Cross-reference this with the employee's "productivity proxy" (orders processed by their store divided by employees at their store) to identify if there's any correlation between performance and stagnation. The CEO wants this broken down by department with anonymized employee IDs.

-- Q8. Swiggy's dark kitchen strategy team needs to evaluate the "ghost kitchen opportunity" in underserved areas. They define an underserved area as a city where: (a) total food delivery orders (category = 'Food' or similar) exceeds ₹20 lakhs annually, (b) no more than 2 stores exist in that city, (c) average delivery time exceeds the company average by at least 1.5 days, (d) customer concentration is high - top 10% of customers in that city account for more than 50% of revenue (indicating loyal base worth serving better), (e) order frequency is above average (repeat customers), BUT (f) basket size is below company average (indicating customers might order more if availability was better). For each qualifying city, calculate the projected revenue uplift if delivery time were reduced to company average, assuming 15% order volume increase.

-- Q9. IRCTC's succession planning committee needs a comprehensive analysis of leadership pipeline depth. Using recursive CTEs, they want to identify "succession gaps" - management positions (employees with at least one direct report) where no viable successor exists. A viable successor is defined as: someone in the manager's direct reports OR indirect reports (up to 2 levels down), whose salary is within 70-95% of the manager's salary (ready for promotion but not already overpaid), who has been with the company for at least 2 years (based on salary_history), and whose "team performance" (if they have reports) shows average team productivity within 80% of the manager's team productivity. Generate a risk report showing positions with 0, 1, and 2+ successors, with recommendations for critical gaps.

-- Q10. Ola's pricing strategy team is testing what they call "surge sensitivity segmentation." They need to identify customer segments based on price sensitivity patterns: (a) "Price Immune" - customers who have ordered even when discounts were less than 5% on their orders and whose average order value exceeds the 75th percentile, (b) "Bargain Hunters" - customers who ONLY order when discounts exceed 15% and whose inter-order gap is less than average (they're actively shopping for deals), (c) "Reluctant Payers" - customers whose order frequency drops by more than 50% in months following any price increase (defined as their average unit_price increasing), (d) "Value Seekers" - customers whose orders show no correlation with discount levels but strong correlation with review ratings of products ordered (they'll pay more for quality). For each segment, calculate the average CLV, recommended pricing strategy, and size of segment.

-- Q11. PhonePe's credit risk team is developing an early warning system they call "The Cascade Indicator." They've observed that late payments tend to cluster geographically and temporally, suggesting economic distress spreading through communities. Build a query that: (a) identifies "distress clusters" - cities where late payments (payment_date > order_date + 5 days) increased by more than 30% month-over-month for any month in the past quarter, (b) for each distress cluster, find the "patient zero" - the first customer in that city to show late payment pattern in the distress period, (c) track the "contagion rate" - how many other customers in that city showed first-time late payment within 30 days of any existing late payer's late payment, (d) identify products most commonly involved in late payments in these clusters (potential trigger categories). Present findings with statistical confidence indicators where possible.

-- Q12. Flipkart's marketplace health team has detected sophisticated "review manipulation rings." These rings operate by having members buy from each other and leave fake positive reviews. Identify potential ring members using this pattern: (a) customers who have reviewed products they purchased with suspicious timing (review within 2 days of delivery, with 5-star rating), (b) where the seller (supplier) of that product has also purchased from products supplied to the reviewer's supplier (circular relationship), (c) the reviewer has reviewed more than 3 products from the same supplier, (d) the reviewer's review text length is suspiciously consistent (standard deviation of review text length < 20 characters across all their reviews), (e) and the reviewer was acquired (joined) within 30 days of the suspicious supplier's first product listing. Group these into potential rings by connected supplier relationships.

-- Q13. BigBasket's subscription box team is designing what they call the "Perfect Box Algorithm." They need to identify products that: (a) are frequently bought together (co-occurrence in same order > 5% of orders containing either), (b) have complementary purchase cycles (if Product A is bought weekly and Product B is bought monthly, suggest both in monthly box), (c) have consistent quality (average rating > 4 with standard deviation < 0.5), (d) have stable availability (never had zero stock for more than 7 consecutive days in the past 6 months), (e) have price stability (max price / min price in order_items < 1.2), and (f) fit the "basket economics" - combined margin (assume 30% margin) on frequently co-purchased items exceeds ₹150 per basket. Generate top 5 product bundles per category with projected margin.

-- Q14. Zomato's restaurant analytics team is building a "Health Score" for restaurant partners (represented as stores). The score combines multiple signals: (a) Order Volume Trend - compare last 30 days orders to 30-60 days ago (>0.9 = healthy), (b) Customer Retention - percentage of customers who ordered more than once from this restaurant (>40% = healthy), (c) Rating Momentum - average rating in last 30 days vs all-time average (declining = unhealthy), (d) Operational Efficiency - percentage of orders delivered on time (<= promised 45 mins, approximated by shipped_date = order_date), (e) Revenue Per Customer - higher than category average = healthy, (f) Complaint Rate - returns with reason containing 'quality' or 'wrong' as percentage of orders (<3% = healthy). Calculate composite health score (average of 6 binary healthy/unhealthy flags), identify restaurants scoring below 3, and for each unhealthy restaurant, identify the top 2 improvement areas (lowest scoring flags).

-- Q15. Amazon India's seller onboarding team needs to identify "Hidden Champion" sellers - suppliers who have potential but haven't broken through yet. Define Hidden Champions as suppliers who: (a) have been supplying for more than 6 months but less than 2 years, (b) have at least 5 products listed, (c) whose best-selling product is in the top 30% of its category but no product is in the top 10% (almost there but not quite), (d) whose customer rating average exceeds category average, (e) whose product return rate is below category average, (f) whose products have never been out of stock (inventory always > 0 when checked), BUT (g) whose total revenue is below median supplier revenue in their tenure bracket. For each Hidden Champion, recommend one action: price reduction, category expansion, or marketing boost, based on which lever would have most impact.

-- Q16. Paytm's customer intelligence team has been asked to build "The Complete Customer Picture" - a 360-degree view that requires pulling together disparate signals. For each customer, calculate: (a) Transaction Behavior Score (0-100 based on frequency, recency, monetary percentile), (b) Engagement Score (0-100 based on email open rate, click rate, campaign response rate), (c) Loyalty Score (0-100 based on tenure, repeat purchase rate, category diversity), (d) Value Trajectory (increasing, stable, decreasing based on quarterly spending trend), (e) Risk Score (0-100 based on late payment tendency, return rate, complaint frequency approximated by low reviews), (f) Influence Score (0-100 based on review count, review helpfulness proxy via text length). Segment customers into archetypes: "Champions" (high value, high loyalty, increasing trajectory), "At Risk" (high value, decreasing trajectory), "Need Nurturing" (low value but high potential based on engagement), etc.

-- Q17. Myntra's supply chain finance team needs to evaluate "Supplier Financing Worthiness" - which suppliers should they offer early payment terms to. Build a scorecard that evaluates each supplier on: (a) Volume Reliability - coefficient of variation of monthly order volume (lower = more reliable), (b) Quality Consistency - standard deviation of product ratings, (c) Price Stability - max/min price ratio across time, (d) Return Exposure - return value as percentage of sales, (e) Customer Dependency - whether top 3 customers account for >50% of their sales (concentration risk), (f) Category Criticality - whether they supply products in categories that are in top 5 by revenue (strategic importance), (g) Substitutability - number of other suppliers in same categories (lower = more critical). Weight these factors (suggest weights based on business logic), calculate composite score, and identify top 10 suppliers for the financing program along with recommended credit limit (as percentage of their monthly average revenue).

-- Q18. Reliance Retail's store operations team is investigating the "Adjacent Cannibalization" problem - when opening a new store, how much does it cannibalize existing stores? Using historical data, for each store that was NOT the first store in its city: (a) identify the "incumbent" stores - stores that existed in the same city before this store opened (based on first order date), (b) calculate the incumbent stores' average monthly revenue in the 6 months BEFORE the new store opened, (c) calculate the same metric for 6 months AFTER, (d) calculate "cannibalization rate" as the percentage decline in incumbents' revenue, (e) correlate cannibalization rate with distance (same city as proxy), (f) calculate "net market creation" - whether total city revenue increased more than new store's revenue (market creation vs redistribution). Summarize findings by region and recommend optimal store density.

-- Q19. Swiggy's delivery fleet optimization team needs to model "Driver Utilization Patterns" (represented as employees with role containing 'delivery' or assigned to orders via store). They want to understand: (a) Peak hour analysis - identify hours where orders per driver (at each store) exceed 150% of daily average for that store, (b) Geographic concentration - stores where top 3 drivers (by order count) handle more than 60% of orders (over-dependence risk), (c) Efficiency variance - within each store, calculate the gap between highest and lowest performing drivers (orders completed per day proxy), (d) Fatigue risk - identify drivers whose order completion in the last 4 hours of their "shift" (later orders in a day) is less than 70% of their first 4 hours, (e) Churn risk - drivers whose daily order counts have been declining for 3 consecutive weeks. For each store, provide a "Fleet Health Score" and top 3 recommendations.

-- Q20. IRCTC's organizational network analysis team needs to understand "Communication Bridges" - employees who connect otherwise disconnected parts of the organization. Using the employee-manager hierarchy: (a) build the complete organizational tree using recursive CTE, (b) for each department, identify employees who have worked across multiple departments (if salary_history or other proxy shows department changes), (c) calculate "bridge score" for each employee - employees who, if removed, would increase the "distance" (levels) between departments they connect, (d) identify "isolated pockets" - departments where no employee has inter-departmental connections, (e) suggest "connector hires" - roles that should be created to bridge isolated pockets, based on adjacent department analysis.

-- Q21. Ola's fraud prevention team has uncovered what they call the "Slow Burn Fraud" - fraudsters who build trust over months before striking. Pattern: (a) customer joins with a referral (if trackable) or from specific campaign, (b) first 3 orders are small (<₹500), well-spaced (>15 days apart), and promptly paid, (c) 4th order shows behavior change - larger amount, different payment mode, (d) subsequent orders escalate rapidly in value with decreasing time between orders, (e) return rate on later orders >50%, (f) total refunded amount exceeds total paid amount (net negative customer), (g) the referring customer (if identifiable through similar patterns or same city/join date cohort) shows similar pattern. Build a risk model that assigns "Slow Burn Probability Score" to all customers based on how many stages of this pattern they've exhibited, with special flag for customers currently in the "trust building" phase.

-- Q22. PhonePe's market basket evolution analysis needs to understand how purchasing patterns change over customer lifecycle. For each customer cohort (defined by join quarter): (a) identify the "entry category" - most commonly purchased category in first order, (b) track "category expansion journey" - average number of months before customer orders from a second category, third category, etc., (c) identify "category loyalty" - categories where repeat rate >60%, (d) calculate "basket maturation curve" - how average basket size changes from month 1 to month 12 of customer lifecycle, (e) identify "graduation triggers" - products whose purchase correlates with customer upgrading to higher value tier, (f) compare cohorts over time - are newer cohorts reaching maturity faster or slower than older cohorts? Use multiple CTEs to build this lifecycle view.

-- Q23. Flipkart's competitive intelligence team (legal, don't worry) wants to understand "Price Position Dynamics." For each product: (a) calculate their "price rank" within category (are they cheapest, mid-tier, or premium?), (b) track how this rank has changed over time based on unit_price in order_items (proxy for price changes), (c) identify "price followers" - products that seem to adjust price within 7 days of competitor (other brand same category) price changes, (d) identify "price leaders" - products whose price changes precede competitor changes, (e) calculate "price elasticity proxy" - correlation between price changes and order volume changes, (f) identify optimal pricing strategy for each product: "follow the leader," "price leadership," or "price stability." Aggregate insights by category and brand.

-- Q24. BigBasket's customer micro-segmentation team is moving beyond traditional RFM. They want to create "Behavioral DNA" profiles combining: (a) Shopping rhythm (weekday vs weekend, morning vs evening based on order_date), (b) Channel affinity (payment mode preferences and patterns), (c) Price sensitivity index (correlation between their order volume and discount levels), (d) Quality consciousness index (average rating of products they purchase), (e) Variety seeking score (number of distinct categories / number of orders), (f) Brand loyalty index (concentration of purchases in top 3 brands), (g) Trend following (do they buy new products early or late in product lifecycle?), (h) Returns behavior (return rate and reasons). Create composite profiles and cluster customers into 5-7 actionable personas using the calculated indices (clustering via SQL using distance calculations between customers).

-- Q25. Zomato's operations excellence team needs to model "Cascade Failure Points" - where does a small problem become a big one? Build an analysis that: (a) identifies orders that experienced multiple issues (delay AND return AND/or low rating), (b) traces back to find common root causes - same store, same courier, same time window, same product, (c) calculates "failure multiplication factor" - how likely is a second failure if first failure occurred, (d) identifies "failure absorption points" - stores or couriers that handle failures without cascade (high problem orders but maintained ratings), (e) builds "failure prediction model" - for a given order, based on time, store, product, courier history, what's the predicted failure probability, (f) recommends "intervention points" - where should they add quality checks to prevent cascades.

-- Q26. Amazon India's marketplace dynamics team is studying "Seller Ecosystem Balance." They need to ensure no single seller dominates while maintaining quality. Build analysis for: (a) Market share analysis by category - sellers whose category share exceeds 30%, (b) Quality-share correlation - do high-share sellers maintain quality or does quality decay? (c) "Challenger identification" - smaller sellers with better metrics (rating, return rate) who could be promoted, (d) "Monopoly risk index" - categories where top 3 sellers have >80% share AND average category rating is declining, (e) "New entrant success rate" - what percentage of sellers survive their first year with positive ratings?, (f) "Optimal competition level" - based on categories with best customer metrics, what's the ideal number of sellers and market share distribution?

-- Q27. Paytm's risk-adjusted revenue analysis needs to calculate "True Revenue" accounting for all risk factors. For each store and time period: (a) Gross Revenue from orders, (b) minus Returns (actual refunded), (c) minus "Expected Returns" (for orders not yet in return window, based on historical return rate for that product/store), (d) minus "Credit Risk Reserve" (for unpaid or late payments, probability-weighted), (e) minus "Fraud Reserve" (orders from customers matching fraud patterns, probability-weighted), (f) minus "Warranty Reserve" (for products with historical warranty claims), (g) calculate "Revenue Quality Score" (Adjusted Revenue / Gross Revenue). Identify stores with lowest revenue quality and root causes.

-- Q28. Myntra's customer journey friction analysis aims to identify "Silent Abandonments" - places where customers stop engaging without explicit feedback. Build: (a) Email funnel - percentage who received email → opened → clicked → converted, identify biggest drop-off point by campaign, (b) Order completion funnel - customers who viewed (ordered) an expensive item then switched to cheaper (next order cheaper) - "sticker shock," (c) "Choice paralysis" - categories where customers browse (order) many items but return most (return rate > 50%), (d) "Repeat hesitation" - customers whose second order takes 2× longer than average second order timing, (e) "Feedback avoidance" - orders without reviews where similar orders (same product, similar customer) typically get reviews - silent dissatisfaction. Quantify revenue impact of each friction type.

-- Q29. Reliance Retail's workforce analytics team is modeling "Team Chemistry Impact." They believe team composition affects store performance beyond individual skills. Build: (a) For each store, calculate team metrics: tenure diversity (standard deviation of employee tenure), salary equity (highest/lowest salary ratio), role mix (percentage in each role), department representation (number of departments), (b) Correlate these with store performance metrics: revenue per employee, customer rating, employee "retention" (proxy: salary growth rate suggests kept employees happy), (c) Identify "magic formula" - team compositions correlated with top decile performance, (d) Identify "toxic combinations" - compositions correlated with bottom decile, (e) For underperforming stores, recommend hiring or restructuring to move toward optimal composition.

-- Q30. Swiggy's predictive inventory system needs to model "Demand Sensing" - predicting stock needs before they become urgent. Build: (a) Calculate "velocity" for each product-store - average daily sales over last 30 days, (b) Calculate "acceleration" - is velocity increasing or decreasing (compare to previous 30 days), (c) Calculate "volatility" - standard deviation of daily sales, (d) Identify "lead time" requirements - for each supplier, average time from stockout to replenishment (proxy from inventory update patterns), (e) Calculate "reorder point" = (velocity × lead time) + (volatility × safety factor), (f) Calculate "reorder quantity" = velocity × 30 days (monthly supply), (g) Flag "immediate action" items where current stock < reorder point, (h) Flag "warning" items where stock will hit reorder point within 7 days based on current velocity. Present as actionable inventory management dashboard.

-- Q31. IRCTC's leadership development program needs to identify "Hidden Leaders" - employees with leadership potential not in management roles. Analyze: (a) Employees whose store's performance improved after they joined (comparing before/after metrics), (b) Employees whose salary growth rate exceeds peers in same role/tenure bracket, (c) Employees at stores where team turnover (proxy: wide variance in salary_history tenure) is low (they help retain colleagues), (d) Employees who have worked across multiple departments (if trackable), (e) Employees at consistently high-performing stores who haven't been promoted (tenure > 3 years, not manager role). Create "Leadership Potential Score" combining these factors and recommend top 10 candidates for development program.

-- Q32. Ola's customer lifecycle monetization team needs to model "Revenue Optimization by Lifecycle Stage." Define stages: Onboarding (first 30 days), Adoption (31-180 days), Maturity (181-365 days), Loyalty (366+ days). For each stage and customer segment: (a) Calculate average revenue per customer, (b) Calculate drop-off rate to next stage, (c) Identify "stage accelerators" - actions that move customers faster through stages (campaign responses, high-value orders, etc.), (d) Identify "stage blockers" - events that stall progression (returns, complaints, long gaps), (e) Calculate "lifetime stage value" - probability-weighted expected revenue if customer follows average progression, (f) Identify "stage skippers" - customers who jump stages (straight to loyalty behavior) and what differentiates them.

-- Q33. PhonePe's payment ecosystem modeling needs to understand "Payment Mode Migration Patterns." Build: (a) Track each customer's payment mode usage over time (percentage by mode per quarter), (b) Identify "migration triggers" - events that precede payment mode switches (high-value order, failed payment, campaign offer), (c) Calculate "mode stickiness" - probability of returning to a mode once used, (d) Identify "destination modes" - where do customers eventually settle? Is there a natural progression (Cash → Card → UPI)?, (e) Calculate "mode lifetime value" - customers using certain modes are worth more/less over time, (f) Identify "profitable migrations" to encourage and "unprofitable migrations" to prevent. Build payment mode recommendation engine based on customer profile and lifecycle stage.

-- Q34. Flipkart's vendor management risk assessment needs to model "Supplier Shock Scenarios." For each critical supplier (top 20 by revenue): (a) Calculate "dependency index" - what percentage of orders would be unfulfillable if this supplier stopped supply?, (b) For each dependent store, calculate "recovery time" - based on alternative suppliers in same category, how long to ramp up supply?, (c) Calculate "customer impact" - how many customers have this supplier's products as >30% of their orders?, (d) Model "cascade effects" - if supplier fails, which customers might churn based on their alternatives?, (e) Calculate "financial exposure" - expected revenue loss for 30-day supplier outage, (f) Rank suppliers by "systemic importance score" combining these factors and recommend risk mitigation strategies (alternative supplier development, safety stock, contract terms).

-- Q35. BigBasket's customer communication optimization needs to model "Message Fatigue" and find optimal contact frequency. Build: (a) Track email engagement over time for each customer - identify the "fatigue point" where open rates drop significantly, (b) Calculate optimal send frequency by customer segment (heavy vs light buyers), (c) Identify "resurrection opportunities" - customers who stopped engaging with emails but are still purchasing (waste), (d) Identify "email dependency" - customers who ONLY buy when they receive email (versus organic purchasers), (e) Calculate "marginal value of email" - incremental revenue per email sent by segment, (f) Build "contact capacity model" - maximum emails per customer per week before fatigue sets in.

-- Q36. Zomato's restaurant recovery program (post-COVID style analysis, hypothetically) needs to identify restaurants that need support. Build "Recovery Priority Score": (a) Calculate revenue decline - compare current quarter to same quarter previous year, (b) Calculate "loyalty erosion" - percentage of previously regular customers (>3 orders) who haven't ordered recently, (c) Calculate "rating pressure" - recent ratings vs historical (declining quality perception), (d) Calculate "market share loss" - restaurant's share of city orders declining faster than market, (e) Calculate "recovery trajectory" - is the restaurant's month-over-month trend improving or worsening?, (f) Calculate "recovery potential" - restaurants with loyal customer base, strong historical metrics but recent decline have high potential. Rank restaurants and recommend intervention type (marketing support, operational support, menu optimization).

-- Q37. Amazon India's cross-selling engine needs to model "Complementarity Scoring" beyond simple co-purchase. Build: (a) Calculate "temporal complementarity" - products bought together within same week vs same day (higher same-day = stronger complement), (b) Calculate "sequential complementarity" - products where buying A increases probability of buying B within 30 days, (c) Calculate "substitute cannibalization" - products where buying A decreases probability of buying competitor B, (d) Calculate "basket anchors" - products that when present, increase overall basket size by >20%, (e) Build "recommendation confidence" - for each product pair, how consistently does co-purchase pattern hold across different customer segments?, (f) Create "cross-sell priority matrix" - for each product, top 3 cross-sell recommendations with expected revenue lift.

-- Q38. Paytm's customer risk evolution modeling needs to track "Risk Trajectory." For each customer: (a) Build risk timeline - track risk indicators (late payments, returns, low ratings given) over their lifecycle, (b) Identify "risk emergence pattern" - do customers become risky suddenly or gradually?, (c) Calculate "risk persistence" - once a customer exhibits risk behavior, do they recover?, (d) Identify "risk triggers" - events that precede risk emergence (large order, life events proxied by address changes if trackable), (e) Calculate "time to risk" - for customers who eventually became risky, how long after joining?, (f) Build "risk staging model" - categorize customers into risk stages (Safe → Watch → At-Risk → High-Risk → Remediation) with transition probabilities.

-- Q39. Myntra's assortment localization needs to model "Regional Style Preferences." For each region: (a) Identify "overperforming categories" - categories where region's share of category sales exceeds region's share of total sales, (b) Identify "underperforming" - opposite of above, (c) Calculate "brand resonance" - brands that perform disproportionately well in each region, (d) Identify "price sensitivity variance" - regions where discount impact on volume is higher/lower than average, (e) Calculate "seasonality patterns" - do different regions have different peak seasons?, (f) Build "regional assortment score" - for each product, how well does it fit each region's preferences?, (g) Recommend "assortment gaps" - product types successful in similar regions but not present in a given region.

-- Q40. Reliance Retail's customer acquisition cost attribution needs to build "True CAC by Channel." Build: (a) Identify first touchpoint (campaign) for each customer who converted, (b) For customers with multiple touchpoints before conversion, build attribution model (first touch, last touch, linear attribution), (c) Calculate channel CAC = (channel budget / attributed conversions), (d) Calculate "channel quality" = average LTV of customers acquired through each channel, (e) Calculate "channel ROI" = (LTV × conversions - budget) / budget, (f) Identify "channel synergies" - channel combinations that perform better than individual channels (customers touched by both), (g) Recommend optimal budget allocation across channels to maximize ROI with constraints.

-- Q41. Swiggy's customer expectation modeling needs to understand "Satisfaction Drivers." Build: (a) Correlate order attributes with ratings - which factors (delivery time, basket size, discount, product category) most predict rating?, (b) Calculate "expectation gap" - for each order, expected rating (based on attributes) vs actual rating - identify orders that underperformed/overperformed expectations, (c) Identify "hygiene factors" - attributes where poor performance drastically reduces rating but great performance doesn't help much, (d) Identify "delight factors" - attributes where great performance significantly boosts rating, (e) Build "satisfaction prediction model" - for a given order configuration, what's the expected rating?, (f) Recommend "minimum viable order" - attribute combination that achieves target rating (4.0) at minimum cost.

-- Q42. IRCTC's strategic workforce planning needs to model "Skills Supply-Demand Gap." Build: (a) For each role, calculate current headcount and salary expenditure, (b) Project "demand" - based on business growth (order growth rate), how many people will be needed in each role in 12 months?, (c) Project "supply" - based on attrition trends and current hiring pipeline, how many will be available?, (d) Calculate "gap" = demand - projected supply, (e) For each role, calculate "criticality" based on its impact on business metrics (productivity correlation), (f) Calculate "time to fill" proxy - roles with higher salary variance are harder to fill, (g) Build "workforce planning priority matrix" - roles with high gap, high criticality, long time-to-fill need immediate action.

-- Q43. Ola's driver experience team (hypothetically mapping to employees) needs to model "Driver Success Factors." Identify: (a) Top quartile performers (by productivity) and their common characteristics (tenure, store, department), (b) "Success predictors" - early indicators that predict eventual top performance (first month metrics), (c) "Performance plateau" - point at which performance growth typically levels off, (d) "Performance decay" - patterns that precede performance decline (leading indicators), (e) "Peer effects" - does working with high performers improve others' performance?, (f) Build "performance potential model" - for each employee, predicted performance ceiling and current utilization of potential.

-- Q44. PhonePe's cohort economics modeling needs to track "Unit Economics by Cohort." For each monthly cohort: (a) Calculate "cohort CAC" - marketing spend in that month / new customers, (b) Track "cohort revenue curve" - cumulative revenue at months 1, 3, 6, 12, (c) Track "cohort profit curve" - revenue minus variable costs (returns, payment processing fees proxy), (d) Calculate "payback period" - months until cumulative profit exceeds CAC, (e) Calculate "terminal LTV" - projected lifetime value at month 36 using retention curves, (f) Calculate "cohort ROI" = (LTV - CAC) / CAC, (g) Compare cohorts over time - are economics improving or worsening? What's driving changes?

-- Q45. Flipkart's marketplace quality governance needs to model "Seller Quality Degradation." Track: (a) Each seller's quality metrics over time (rating, return rate, delivery performance), (b) Identify "quality decay pattern" - sellers whose metrics worsen after reaching certain volume threshold, (c) Calculate "quality-volume tradeoff" - correlation between volume growth and quality decline, (d) Identify "quality stabilizers" - sellers who maintain quality at scale - what differentiates them?, (e) Calculate "quality half-life" - for sellers who start declining, how long until quality becomes unacceptable?, (f) Build "intervention triggers" - metric thresholds that should trigger proactive outreach before sellers become problematic.

-- Q46. BigBasket's demand planning needs to model "Demand Shaping Opportunities." Identify: (a) Products with high "elasticity" - where price/promotion changes significantly impact demand, (b) Products with "demand shifting" potential - can demand be moved from peak times to off-peak?, (c) "Substitution patterns" - when product A is unavailable, which products absorb its demand?, (d) "Cannibalization quantification" - when promoting product A, how much does it cannibalize similar products?, (e) "Demand creation" - products where marketing creates new demand vs just shifting timing, (f) Build "promotion ROI model" - for each product, expected volume lift, revenue impact net of cannibalization, and margin impact.

-- Q47. Zomato's partner revenue optimization (restaurant as store) needs "Revenue Maximization Modeling." For each restaurant: (a) Calculate "peak capacity utilization" - orders during peak hours vs theoretical maximum, (b) Identify "menu optimization opportunities" - high-margin items that are under-ordered vs over-promoted low-margin items, (c) Calculate "customer concentration risk" - percentage of revenue from top 10% customers, (d) Identify "daypart opportunities" - time slots with low utilization that could be developed, (e) Calculate "average ticket optimization" - gap between current basket size and what similar restaurants achieve, (f) Build "revenue improvement playbook" - top 3 recommendations per restaurant with expected impact.

-- Q48. Amazon India's fulfillment network modeling needs "Cost-to-Serve Analysis." For each customer: (a) Calculate "service cost" - shipping costs, returns processing, customer service contacts (proxy from return reasons), (b) Calculate "gross margin" = revenue - product cost (proxy as 70% of price), (c) Calculate "net margin" = gross margin - service cost, (d) Identify "unprofitable customers" - negative net margin, (e) Identify "cost drivers" - what behaviors drive high service costs? (returns, remote location, payment failures), (f) Build "profitability improvement actions" - for each unprofitable customer, which single behavior change would make them profitable?

-- Q49. Paytm's product recommendation personalization needs "Affinity Modeling." For each customer: (a) Build "category affinity vector" - purchase probability by category based on history, (b) Build "brand affinity vector" - similar for brands, (c) Build "price affinity" - typical price point they purchase at, (d) Build "quality affinity" - typical rating of products they purchase, (e) Calculate "exploration tendency" - how often do they buy outside their typical profile?, (f) For each product, calculate "affinity score" - how well does it match this customer's profile?, (g) Recommend products with highest affinity that customer hasn't purchased yet, with confidence level.

-- Q50. Myntra's customer retention economics needs "Churn Cost Quantification." Build: (a) Define "churned" as no order in 90 days, (b) Calculate "churn probability" for each customer based on behavior signals, (c) Calculate "expected remaining LTV" for each customer - future revenue if they don't churn, (d) Calculate "churn cost" = churn probability × expected LTV, (e) Calculate "save probability" - based on historical data, what percentage of at-risk customers respond to retention efforts?, (f) Calculate "optimal retention spend" = churn cost × save probability, (g) Prioritize retention efforts by net expected value (save probability × LTV - retention cost).

-- Q51. Reliance Retail's location strategy modeling needs "Gravity Model for Store Performance." Build: (a) For each store, calculate "catchment area" - cities within same state (proxy for distance), (b) Calculate "market potential" = sum of (population proxy × income proxy / distance proxy) for each city in catchment, (c) Correlate market potential with actual store performance, (d) Identify "over-performing" stores - performance >> market potential (operational excellence), (e) Identify "under-performing" stores - performance << potential (execution issues), (f) For each city without a store, calculate "opportunity score" based on market potential and distance to nearest existing store.

-- Q52. Swiggy's delivery logistics optimization needs "Route Efficiency Modeling." Build: (a) For each delivery route (store to customer city), calculate average delivery time, (b) Identify "bottleneck routes" - routes where delivery time significantly exceeds distance-expected time (proxy from city-to-city patterns), (c) Calculate "time of day effects" - how does route efficiency vary by hour?, (d) Calculate "volume effects" - do high-volume routes have better or worse efficiency?, (e) Identify "route alternatives" - orders that could be served from different stores with better efficiency, (f) Build "routing recommendations" - orders that should be rerouted and expected time savings.

-- Q53. IRCTC's compensation strategy team needs "Pay Equity Analysis." Build: (a) Expected pay model - predict salary based on role, tenure, department, store performance, (b) Calculate "pay gap" = actual salary - expected salary for each employee, (c) Identify "overpaid" (positive gap) and "underpaid" (negative gap) employees, (d) Analyze gaps by demographics if available (or department/role as proxy), (e) Calculate "internal equity ratio" - for same role, ratio of highest to lowest paid, (f) Identify "compression issues" - where new hires are paid similar to experienced employees, (g) Build "equity adjustment recommendations" with prioritized list and budget impact.

-- Q54. Ola's service recovery economics needs "Failure Response ROI." Build: (a) Identify orders with failures (late delivery, returns, low rating), (b) Track customer behavior post-failure - did they return? How soon? What was their next order value?, (c) Calculate "organic recovery rate" - percentage who return without intervention, (d) For customers who received recovery action (discount code, etc. - proxy through subsequent discounted orders), calculate "intervention recovery rate," (e) Calculate "intervention ROI" = (incremental retention × LTV - intervention cost), (f) Identify "optimal intervention level" - point where marginal ROI of additional intervention decreases.

-- Q55. PhonePe's business model evolution needs "Revenue Stream Diversification Analysis." Build: (a) Calculate revenue concentration by category - Herfindahl index, (b) Track concentration over time - is business becoming more or less diversified?, (c) Identify "growth engines" - categories growing faster than overall, (d) Identify "declining cores" - historically important categories now shrinking, (e) Calculate "revenue stability" - categories with lower volatility provide more stable revenue, (f) Build "portfolio optimization" - recommend category mix that balances growth potential and stability.

-- Q56. Flipkart's advertising effectiveness modeling needs "Ad Spend Attribution." For each campaign: (a) Define "exposed" customers - those who received campaign emails, (b) Define "control" - similar customers who didn't receive, (c) Calculate "lift" = (exposed conversion rate - control conversion rate), (d) Calculate "attributed revenue" = lift × exposed customers × average order value, (e) Calculate "ROAS" = attributed revenue / campaign budget, (f) Identify "campaign characteristics" that correlate with high ROAS (timing, targeting, discount level), (g) Build "campaign optimization model" - predict expected ROAS for proposed campaigns.

-- Q57. BigBasket's working capital optimization needs "Inventory Investment ROI." For each product: (a) Calculate "inventory holding cost" = average stock × price × 2% monthly holding cost, (b) Calculate "gross margin generated" from sales, (c) Calculate "inventory ROI" = gross margin / holding cost, (d) Identify "cash traps" - high inventory, low turnover, low ROI, (e) Identify "stock-out cost" - estimate lost sales during stockout periods, (f) Calculate "optimal inventory level" that balances holding cost vs stockout cost, (g) Recommend "inventory rebalancing" - products to reduce stock and products to increase.

-- Q58. Zomato's dynamic pricing potential needs "Price Sensitivity Mapping." Build: (a) Track price-volume relationships for each product (from order_items unit_price variations), (b) Calculate "price elasticity" = % change in volume / % change in price, (c) Segment products by elasticity: highly elastic (commodity), inelastic (differentiated), (d) Identify "price optimization opportunities" - inelastic products where price increase would increase revenue, (e) Identify "volume optimization opportunities" - elastic products where price decrease would increase revenue enough to offset margin loss, (f) Calculate "optimal price" for each product to maximize profit.

-- Q59. Amazon India's seller ecosystem balance needs "Marketplace Health Index." Build: (a) "Competition health" - number of sellers, Herfindahl index by category, (b) "Quality health" - average rating trend, return rate trend, (c) "Customer health" - customer acquisition rate, retention rate, NPS proxy (5-star reviews), (d) "Seller health" - seller retention, new seller success rate, seller satisfaction proxy (continued supply), (e) "Economic health" - GMV growth, take rate (margin proxy), transaction size, (f) Combine into composite index, track over time, identify leading indicators of overall health.

-- Q60. Paytm's customer communication sequencing needs "Journey Optimization." Build: (a) Map typical customer journey - touchpoints and order of engagement, (b) Identify "journey friction points" - where do customers typically drop off?, (c) Identify "journey accelerators" - touchpoints that speed up conversion, (d) Calculate "optimal journey length" - how many touchpoints before conversion with diminishing returns?, (e) Identify "personalization opportunities" - points where different customers need different journeys, (f) Build "journey recommendation engine" - for each customer, what's the optimal next touchpoint?

-- Q61. Myntra's trend detection system needs "Fashion Velocity Modeling." Build: (a) Track category growth rates over rolling 4-week periods, (b) Identify "emerging trends" - categories accelerating growth, (c) Identify "declining trends" - categories decelerating, (d) Calculate "trend maturity" - how far into the trend cycle is each category?, (e) Identify "leading indicators" - categories that trend before others (fashion leaders), (f) Build "trend forecast" - predict which categories will trend next quarter based on patterns.

-- Q62. Reliance Retail's omnichannel measurement needs "Channel Attribution." For customers who interact with multiple stores (proxy for channels): (a) Track "first touch" store - which store acquired the customer?, (b) Track "last touch" store - which store serves most recent order?, (c) Calculate "channel journey" - how do customers move between stores?, (d) Identify "channel influencers" - stores that appear in journey but not for purchase (research behavior proxy), (e) Build "multi-touch attribution" - distribute credit across journey touchpoints, (f) Calculate "true channel value" including influence, not just direct sales.

-- Q63. Swiggy's customer emotion mapping needs "Sentiment Proxy Modeling." Build: (a) Classify orders into sentiment categories based on rating, return behavior, repeat timing, (b) Identify "sentiment trends" - is customer sentiment improving or declining over time?, (c) Calculate "sentiment triggers" - what order attributes correlate with positive/negative sentiment?, (d) Identify "sentiment at risk" customers - neutral sentiment trending negative, (e) Calculate "sentiment value" - do high-sentiment customers have higher LTV?, (f) Build "sentiment intervention model" - actions that can shift sentiment positive.

-- Q64. IRCTC's organizational agility measurement needs "Decision Velocity Analysis." Build (using whatever proxies available): (a) Track "change implementation speed" - how quickly do organizational changes (salary updates, role changes) happen?, (b) Identify "agile units" - departments/stores that implement changes faster, (c) Identify "bottlenecks" - where do changes get stuck?, (d) Calculate "agility cost" - do faster-changing units have higher or lower costs?, (e) Calculate "agility benefit" - do faster-changing units have better business metrics?, (f) Build "agility optimization" - where should organization invest in faster decision-making?

-- Q65. Ola's market expansion economics needs "New Market Entry Modeling." For stores opened in the past year: (a) Calculate "time to breakeven" - months until store generates positive margin, (b) Identify "success predictors" - market characteristics that predict faster breakeven, (c) Calculate "learning curve" - how does performance improve month over month?, (d) Calculate "optimal entry strategy" - characteristics of markets where stores succeed, (e) Identify "exit candidates" - stores unlikely to ever breakeven based on trajectory, (f) Build "expansion prioritization model" - rank potential markets by expected ROI.

-- Q66. PhonePe's product-market fit measurement needs "Engagement Quality Index." For each product category: (a) Calculate "usage intensity" - orders per active customer, (b) Calculate "usage breadth" - percentage of customers who have ordered, (c) Calculate "retention impact" - does ordering this category improve overall retention?, (d) Calculate "monetization efficiency" - revenue per engaged customer, (e) Build "product-market fit score" combining these metrics, (f) Identify "product-market fit gaps" - categories with high potential but low fit scores.

-- Q67. Flipkart's customer education ROI needs "Learning Effect Measurement." Track: (a) Customer behavior change after first experience with new feature (new category, new payment mode), (b) Calculate "learning curve" - how many interactions until behavior stabilizes?, (c) Identify "education multipliers" - features where small investment in education yields large behavior change, (d) Calculate "education ROI" - revenue from changed behavior vs education cost (campaign cost proxy), (e) Build "education priority matrix" - which behaviors are worth investing to change?

-- Q68. BigBasket's supply chain resilience needs "Disruption Impact Modeling." Build: (a) Identify historical supply disruptions (periods where inventory dropped unexpectedly), (b) Track "disruption impact" - how did orders change during disruption?, (c) Calculate "customer tolerance" - at what stockout duration do customers churn?, (d) Identify "substitution patterns" - when disrupted, what alternatives did customers choose?, (e) Calculate "disruption cost" = lost revenue + customer acquisition cost for churned customers, (f) Build "resilience investment model" - where does investment in redundancy pay off?

-- Q69. Zomato's network effect modeling needs "Density Economics." Build: (a) Calculate "customer density" in each city - customers per proxy population, (b) Calculate "supply density" - stores (restaurants) per area, (c) Correlate density with unit economics - do denser markets have better margins?, (d) Identify "network effects" - does adding more supply improve customer metrics? Does adding customers attract more supply?, (e) Calculate "minimum viable density" - threshold where network effects become positive, (f) Build "density investment model" - should investment go to demand or supply side in each market?

-- Q70. Amazon India's long-tail economics needs "Niche Product Viability." Build: (a) Segment products by sales volume into head, torso, tail, (b) Calculate unit economics for each segment - are long-tail products profitable?, (c) Identify "long-tail enablers" - product characteristics that make long-tail profitable, (d) Calculate "tail customer value" - do customers who buy tail products have different LTV?, (e) Identify "tail to torso" candidates - long-tail products with potential to move up, (f) Build "assortment strategy" - optimal mix of head/torso/tail products.

-- Q71. Paytm's behavioral economics testing needs "Nudge Effectiveness Measurement." Identify: (a) Price anchoring - orders where a higher price shown first influenced final purchase, (b) Scarcity effects - orders influenced by low stock messaging (if trackable through timing), (c) Social proof - orders following high ratings/reviews, (d) Default effects - orders using suggested/default options, (e) Calculate "nudge lift" for each type - how much incremental revenue?, (f) Identify "ethical boundaries" - nudges that improve vs degrade customer welfare.

-- Q72. Myntra's personal stylist economics needs "Recommendation ROI." Build: (a) Track "recommendation adoption" - when products are shown (ordered) in bundles, what percentage of bundle is purchased?, (b) Calculate "recommendation accuracy" - do recommended products get returned less than average?, (c) Calculate "recommendation revenue" - incremental sales from recommendations vs random selection, (d) Identify "recommendation receptiveness" - which customers respond most to recommendations?, (e) Build "recommendation personalization" - how to tailor recommendation strategy by customer segment?

-- Q73. Reliance Retail's real estate strategy needs "Location Value Modeling." For each store: (a) Calculate "location yield" = revenue per square foot proxy (revenue / employee count as size proxy), (b) Calculate "location efficiency" = profit margin × yield, (c) Identify "location optimization opportunities" - high-traffic but low-conversion stores, (d) Calculate "expansion potential" - stores with demand exceeding capacity, (e) Calculate "consolidation candidates" - stores with overlapping catchments and excess capacity, (f) Build "location strategy" - expand, consolidate, or optimize each store.

-- Q74. Swiggy's gig economy dynamics need "Worker Economic Modeling." For delivery staff (employees with relevant roles): (a) Calculate "earnings per hour" proxy from productivity metrics, (b) Track "earnings stability" - consistency of earnings over time, (c) Identify "earnings optimization behaviors" - what do high earners do differently?, (d) Calculate "platform dependence" - what percentage of earnings comes from this platform?, (e) Identify "churn predictors" - earnings patterns that precede exit, (f) Build "earnings optimization recommendations" for workers.

-- Q75. IRCTC's knowledge management needs "Expertise Mapping." Build: (a) Map "expertise areas" by department/role combination, (b) Identify "expertise depth" - tenure in specialized roles, (c) Identify "expertise uniqueness" - roles where few people have the expertise, (d) Calculate "expertise risk" - critical expertise held by retirement-age (high tenure) employees, (e) Identify "expertise gaps" - roles with no clear expertise holders, (f) Build "knowledge transfer priority" - where should documentation and training focus?

-- Q76. Ola's marketplace quality vs growth tradeoff needs "Growth Quality Analysis." Build: (a) Track growth rate (order volume growth) and quality metrics (rating, returns) over time, (b) Identify "sustainable growth" periods - growth without quality decline, (c) Identify "unsustainable growth" periods - growth accompanied by quality decline, (d) Calculate "quality-adjusted growth" = growth rate × (1 - quality decline rate), (e) Identify "growth levers" - which growth tactics damage quality vs which don't?, (f) Build "optimal growth strategy" balancing speed and quality.

-- Q77. PhonePe's customer lifetime modeling needs "Dynamic LTV Calculation." Build: (a) For each customer, calculate "historical LTV" - actual value to date, (b) Calculate "trajectory" - is LTV accelerating, stable, or decelerating?, (c) Project "future LTV" based on trajectory and cohort patterns, (d) Calculate "LTV uncertainty" - range of possible outcomes, (e) Identify "LTV inflection points" - events that significantly change trajectory, (f) Build "LTV maximization actions" - interventions at specific lifecycle points to boost trajectory.

-- Q78. Flipkart's returns economics needs "Reverse Logistics Optimization." Build: (a) Calculate "return cost" by product category - processing, restocking, damage, (b) Calculate "return revenue recovery" - percentage of returned products resold, (c) Calculate "net return cost" = processing cost - recovery value, (d) Identify "high-cost return patterns" - which products/customers/reasons drive highest costs?, (e) Calculate "return prevention ROI" - if we invest X in reducing returns, what's the payback?, (f) Build "returns strategy" - which returns to prevent vs which to accept.

-- Q79. BigBasket's sustainable growth metrics need "Growth Accounting." Build: (a) Decompose growth into: new customer revenue, retained customer revenue growth, churned customer revenue loss, (b) Calculate "growth efficiency" = new revenue / customer acquisition cost, (c) Calculate "retention contribution" = revenue from retained customers / total revenue, (d) Calculate "growth sustainability" = (new + growth) / churn - if > 1, growth is sustainable, (e) Identify "growth bottleneck" - which component is limiting growth?, (f) Build "growth acceleration plan" targeting the constraint.

-- Q80. Zomato's restaurant portfolio strategy needs "Partner Tiering Model." Build: (a) Score each restaurant on: volume contribution, margin contribution, customer quality (ratings, retention), growth potential, (b) Create tier definitions: Platinum, Gold, Silver, Bronze based on scores, (c) Define tier benefits and requirements, (d) Identify "tier movement candidates" - restaurants close to promotion or demotion, (e) Calculate "tier economics" - average profitability by tier, (f) Build "portfolio optimization" - optimal distribution across tiers.

-- Q81. Amazon India's fraud vs friction tradeoff needs "Risk Threshold Optimization." Build: (a) Current fraud detection - orders flagged and blocked, (b) Calculate "false positive cost" - legitimate orders blocked × average order value, (c) Calculate "false negative cost" - fraud losses from undetected cases, (d) Calculate "total cost" at current threshold, (e) Model "cost curves" at different detection thresholds, (f) Calculate "optimal threshold" minimizing total cost, (g) Identify "segment-specific thresholds" - different risk tolerance for different customer segments.

-- Q82. Paytm's business cycle adaptation needs "Seasonality Response Modeling." Build: (a) Decompose business metrics into: trend, seasonality, cyclical, random components, (b) Identify "seasonality drivers" - which categories drive seasonal patterns?, (c) Calculate "seasonality amplitude" - how extreme are seasonal swings?, (d) Identify "counter-seasonal opportunities" - categories that could fill seasonal troughs, (e) Build "seasonal response playbook" - actions to take in each season to optimize performance.

-- Q83. Myntra's customer development economics needs "Share of Wallet Growth." Build: (a) Estimate customer's total fashion spend (based on demographics, order patterns), (b) Calculate current "share of wallet" = Myntra spend / estimated total spend, (c) Identify "wallet expansion opportunities" - customers with low share but high engagement, (d) Calculate "wallet expansion tactics" - which actions have historically increased share?, (e) Build "wallet prioritization" - which customers to focus on for wallet growth?

-- Q84. Reliance Retail's operational excellence needs "Efficiency Frontier Analysis." Build: (a) For each store, calculate input (costs: salaries, expenses) and output (revenue, customer satisfaction), (b) Identify "efficiency frontier" - stores achieving best output for given input level, (c) Calculate "efficiency gap" for each store - distance from frontier, (d) Identify "efficiency improvement levers" - what do frontier stores do differently?, (e) Calculate "efficiency improvement potential" - if all stores reached frontier, what's the gain?, (f) Build "efficiency roadmap" for underperforming stores.

-- Q85. Swiggy's platform economics need "Two-Sided Market Balance." Build: (a) Track "supply-demand balance" - ratio of available restaurants to active customers by city, (b) Identify "supply-constrained" markets - high customer activity, low restaurant options, (c) Identify "demand-constrained" markets - opposite, (d) Calculate "market equilibrium" - what balance produces best unit economics?, (e) Calculate "rebalancing actions" needed in each market, (f) Build "market development priority" based on distance from equilibrium and market potential.

-- Q86. IRCTC's organizational design needs "Span of Control Optimization." Build: (a) Map current organizational structure using recursive CTE, (b) Calculate span of control for each manager, (c) Identify "overstretched managers" - span > 10 with performance issues, (d) Identify "underutilized managers" - span < 4 with capable teams, (e) Calculate "optimal span" by role type based on performance correlations, (f) Recommend "restructuring" to optimize spans across organization.

-- Q87. Ola's customer micro-moment targeting needs "Intent Detection." Build: (a) Identify "purchase intent signals" - behaviors that precede purchase (browsing patterns, cart additions proxy via order patterns), (b) Calculate "intent intensity" - how strong is the purchase signal?, (c) Calculate "intent timing" - how far from conversion is the customer?, (d) Identify "intent intervention points" - when should we engage?, (e) Calculate "intervention impact" - how much does well-timed intervention increase conversion?, (f) Build "intent-based targeting" model.

-- Q88. PhonePe's service disaggregation needs "Revenue Stream Profitability." Build: (a) Disaggregate revenue by: product sales, payment processing (proxy), advertising (campaigns), data (reports), (b) Allocate costs to each stream, (c) Calculate "stream profitability" for each, (d) Identify "cross-subsidies" - streams that subsidize others, (e) Calculate "standalone viability" - could each stream survive independently?, (f) Build "revenue mix optimization" - optimal balance of streams.

-- Q89. Flipkart's customer cohort genetics needs "Acquisition Source DNA." Build: (a) Track customer performance by acquisition source (campaign or organic), (b) Calculate "source quality" - LTV by acquisition source, (c) Identify "source persistence" - do source differences fade over time or persist?, (d) Calculate "source cost efficiency" - CAC × volume by source, (e) Calculate "optimal acquisition mix" - allocation across sources to maximize portfolio value, (f) Build "source performance forecast" for budget planning.

-- Q90. BigBasket's customer service economics needs "Support Cost Attribution." Build: (a) Estimate support contacts by: returns, complaints, inquiries (proxy from return reasons, low ratings), (b) Calculate "contact cost" by type, (c) Attribute support costs to products, customers, stores, (d) Calculate "net margin" after support costs by customer, (e) Identify "support cost drivers" - which products/experiences generate most support need?, (f) Build "support cost reduction" priority based on addressable causes.

-- Q91. Zomato's restaurant lifecycle management needs "Partner Maturity Model." Build: (a) Define maturity stages: Onboarding, Growth, Maturity, Decline, (b) Classify each restaurant into stage based on metrics trends, (c) Calculate "stage transition probabilities" - likelihood of moving between stages, (d) Identify "stage accelerators" - actions that speed positive transitions, (e) Identify "stage blockers" - factors that prevent progression, (f) Build "lifecycle management playbook" for each stage.

-- Q92. Amazon India's competitive response system needs "Competitive Position Monitoring." Build: (a) For each category, calculate market share (if multiple brands/suppliers represent competitors), (b) Track "share movement" over time, (c) Identify "competitive threats" - categories with declining share, (d) Identify "competitive opportunities" - categories with growing share, (e) Calculate "response effectiveness" - when action was taken (promotion, price change), did share improve?, (f) Build "competitive response playbook" by category situation.

-- Q93. Paytm's customer health scoring needs "360-Degree Health Index." Combine: (a) Financial health - payment timing, order value trends, returns, (b) Engagement health - email interaction, order frequency, category exploration, (c) Satisfaction health - ratings given, review sentiment proxy (length, frequency), (d) Loyalty health - tenure, share of wallet proxy, referral activity proxy, (e) Create composite "Customer Health Score," (f) Identify "health trajectories" - improving, stable, declining, (g) Build "health intervention" recommendations by trajectory.

-- Q94. Myntra's assortment productivity needs "SKU Rationalization." Build: (a) Calculate revenue and margin contribution by product, (b) Calculate "inventory investment" by product, (c) Calculate "productivity" = margin / inventory investment, (d) Identify "productivity stars" vs "productivity drags," (e) Calculate "exit impact" - if we removed low-productivity SKUs, what's the revenue at risk vs inventory freed?, (f) Build "rationalization recommendation" - products to exit, products to promote.

-- Q95. Reliance Retail's talent marketplace needs "Internal Mobility Analysis." Build: (a) Track employee movements between stores, departments, roles (via salary_history patterns), (b) Identify "talent sources" - which units develop people who move to other units?, (c) Identify "talent sinks" - which units receive talent but don't develop for others?, (d) Calculate "mobility impact" - do mobile employees perform better?, (e) Calculate "mobility cost-benefit" - cost of backfilling vs benefit of placing talent optimally, (f) Build "internal talent marketplace" recommendations.

-- Q96. Swiggy's capital efficiency needs "Asset Utilization Analysis." Build: (a) Calculate "inventory asset" = average stock value, (b) Calculate "receivables asset" = average unpaid orders proxy, (c) Calculate "asset turnover" = revenue / (inventory + receivables), (d) Benchmark against industry or across stores, (e) Identify "capital efficiency opportunities" - where could turnover improve?, (f) Calculate "capital efficiency value" - if turnover improved to benchmark, how much capital freed?

-- Q97. IRCTC's organizational culture needs "Engagement Economics." Build: (a) Proxy "engagement" from retention (tenure), productivity, salary growth, (b) Correlate engagement with business metrics, (c) Calculate "engagement-performance multiplier" - how much does 1 unit of engagement improve performance?, (d) Calculate "engagement investment ROI" - if we invest X in engagement initiatives, what's the performance return?, (e) Identify "engagement drivers" - which factors most impact engagement?, (f) Build "engagement investment priority."

-- Q98. Ola's market dominance economics needs "Market Share Value Analysis." Build: (a) Calculate market share by city/category, (b) Calculate "market share premium" - do categories with higher share have better margins?, (c) Calculate "scale effects" - relationship between volume and unit costs, (d) Calculate "share threshold" - point where scale effects become significant, (e) Identify "share build vs harvest" - markets where share investment pays off vs markets to milk, (f) Build "market strategy" by share position.

-- Q99. PhonePe's ecosystem economics needs "Platform Value Creation." Build: (a) Calculate "total ecosystem value" = sum of all participant value (customers + sellers), (b) Track "value distribution" - what percentage goes to customers, sellers, platform?, (c) Calculate "value creation vs value capture" - is platform creating new value or redistributing?, (d) Identify "value creation levers" - where does platform add most value?, (e) Calculate "sustainable value share" - what platform take rate is sustainable long-term?, (f) Build "ecosystem health metrics" for ongoing monitoring.

-- Q100. Flipkart's ultimate business intelligence challenge: Using everything you've learned about CTEs, correlated subqueries, and advanced SQL, build a comprehensive "Business Cockpit" query that brings together: (a) CTE for Customer Health metrics across all segments, (b) CTE for Product Performance across all categories, (c) CTE for Store Operations efficiency metrics, (d) CTE for Financial Performance with revenue, costs, margins, (e) CTE for Employee Productivity by role and store, (f) CTE for Marketing Effectiveness across campaigns, (g) Correlated subqueries to benchmark each metric against relevant peers, (h) Final SELECT that creates an executive dashboard with traffic-light indicators (green/yellow/red) for each business area, trend direction (improving/stable/declining), and top 3 recommended actions based on which areas are most critical. This query should be the synthesis of all Day 12 concepts and demonstrate mastery of advanced SQL without using window functions.

-- ============================================
-- END OF DAY 12 CRAZY HARD QUESTIONS
-- ============================================
