-- ============================================
-- Day 11: Subqueries Part 1 - CRAZY HARD Level
-- Student Question Bank (100 Questions)
-- ============================================
-- Concepts Allowed: SELECT, FROM, WHERE, JOINs (all types), 
--   GROUP BY, HAVING, Aggregates, CASE WHEN, COALESCE, NULLIF,
--   Set Operations (UNION, INTERSECT, EXCEPT), Self Join, Cross Join,
--   Subqueries (scalar, multi-row), IN/NOT IN with subqueries,
--   EXISTS/NOT EXISTS, Subqueries in WHERE/SELECT/FROM
-- Concepts NOT Allowed: Correlated subqueries, ANY/SOME/ALL,
--   CTEs, Window Functions, Transactions, Views, Functions
-- ============================================

-- Q1. Flipkart's CEO has called an emergency board meeting. The finance team has discovered that certain premium product categories are generating 80% of the revenue but only contain 15% of the products. However, during the Diwali season, this pattern reverses. The board wants a comprehensive analysis identifying: (a) which categories exhibit this "Pareto effect" where top 20% products generate 80% revenue, (b) within those categories, which specific products are in the elite top 20%, (c) exclude any products that have had returns exceeding 5% of their total orders. The CFO is particularly concerned about products from suppliers who have less than 95% on-time delivery rate. Prepare the analysis showing category, product name, revenue contribution percentage, and supplier reliability score.

-- Q2. Zomato's Chief Strategy Officer is evaluating whether to pivot their dark kitchen strategy. The hypothesis is that in cities where customer ordering patterns show high lunch-hour concentration (between 11 AM and 2 PM orders exceeding 40% of daily orders - you'll need to approximate using date patterns), dark kitchens outperform traditional restaurants. However, the analysis must exclude cities where: (i) Zomato has fewer stores than the national average stores per city, (ii) the average customer has placed fewer than 3 orders in the last quarter, (iii) return rates exceed the company average by more than 1.5 standard deviations. For qualifying cities, rank them by the ratio of (revenue per kitchen staff) to (average delivery time), where kitchen staff is approximated by employees with 'Kitchen' in their role.

-- Q3. BigBasket's newly appointed VP of Procurement has inherited a vendor portfolio that the previous management let grow chaotically. She needs to implement a "Vendor Rationalization Matrix" that categorizes suppliers into four quadrants: (1) Strategic Partners - high volume, high quality (low returns), competitive pricing (below category average); (2) Leverage Candidates - high volume, acceptable quality, but pricing above average; (3) Development Suppliers - low volume but exceptional quality that could be grown; (4) Exit Candidates - below average on at least two dimensions. The twist: "volume" should be normalized against the category average, "quality" is returns percentage vs category, and "pricing" is supplier average price vs category average. Generate the complete matrix with supplier names, their quadrant assignment, and the three underlying scores.

-- Q4. Myntra's Head of Customer Lifecycle is presenting to investors next week about customer cohort behavior. They need an analysis that shows: for customers who made their first purchase in each quarter of last year, (a) what percentage upgraded to "heavy buyer" status (top 25% by order frequency) within 6 months, (b) what was their average order value compared to customers acquired through email campaigns (check email_clicks for campaign association), (c) which product categories did "retained" customers (those who ordered in the last month) prefer compared to "churned" customers (no orders in last 3 months). The analysis must exclude customers who were clearly B2B buyers (indicated by order patterns exceeding 10 orders per month average).

-- Q5. PhonePe's Risk Committee is investigating a concerning pattern. Their fraud ML model flagged customers whose payment behavior shows "structuring" - splitting what should be single purchases into multiple smaller payments to avoid detection thresholds. Identify customers where: (a) they have multiple payments on the same day to the same store that together exceed ₹10,000, (b) but each individual payment is below ₹2,500, (c) and this pattern occurs more than twice across different dates. However, exclude customers whose overall return rate is below average (these are likely legitimate high-frequency buyers). For flagged customers, show their total structured amount, number of structuring incidents, and their "risk score" calculated as (structured amount / total lifetime spend).

-- Q6. Ola's newly hired Chief People Officer discovered that the company has no systematic approach to compensation benchmarking. She wants to identify "compensation anomalies" - employees whose salary deviates significantly from peers. The analysis is complex: (a) "peers" are defined as employees in the same role AND same region AND with ±2 years of experience (approximate using join date), (b) "significant deviation" means more than 1.5 standard deviations from peer average, (c) but this must be weighted by store performance - underpaid employees at high-performing stores (above average revenue) are priority concerns. Generate a report showing employee name, their salary, peer average, deviation percentage, store performance percentile, and urgency flag (High/Medium/Low).

-- Q7. Amazon India's Supply Chain AI team is building a demand sensing model. They need historical data that shows "demand signals" - instances where actual demand exceeded predicted patterns. Using historical order data as the baseline, identify products where: (a) orders on any given day exceeded that product's 30-day moving average by more than 2 standard deviations, (b) this spike occurred within 7 days of a marketing campaign for that product's category, (c) but was NOT during a known promotion period (between promo start and end dates). For these demand spike events, calculate the "signal strength" as (actual orders / expected orders) and correlate with whether the spike led to stockouts (inventory reaching zero within 3 days of the spike).

-- Q8. Swiggy's Restaurant Success team has a controversial hypothesis: restaurants that maintain a "curated" menu (fewer items but higher quality) outperform those with extensive menus. The analysis must: (a) classify stores into "curated" (distinct products ordered < category median) vs "extensive" (> category median), (b) for each group, calculate average revenue, average rating, and repeat customer percentage (customers who ordered 3+ times from same store), (c) but only compare stores within the same city to control for market effects, (d) exclude stores that are less than 6 months old (first order date). Present findings with statistical summary showing which strategy wins on each metric, and whether the pattern holds across different city tiers (metro vs non-metro based on customer density).

-- Q9. IRCTC's Revenue Management division is optimizing their pricing algorithm. They need to identify "price elasticity clusters" - products where demand behavior follows similar patterns when prices change. The analysis requires: (a) identifying products where there were multiple distinct price points (different unit_price in order_items - minimum 3 different prices), (b) calculating the demand change percentage for each price change, (c) clustering products as "elastic" (demand changed by more than 10% when price changed by 5%) or "inelastic", (d) within elastic products, further sub-classify as "luxury elastic" (higher prices = lower demand) or "Veblen goods" (higher prices = higher demand). For each cluster, show representative products, their price range, and demand range.

-- Q10. Reliance Retail's newly formed Customer Intelligence unit is building "Customer DNA" profiles. They want to identify hidden customer segments using purchase behavior, not demographics. The analysis involves: (a) calculating each customer's "category affinity" scores (percentage of spend in each category), (b) identifying customers whose affinity pattern matches the profile of top 10% spenders (affinity percentages within 10% of elite customer average per category), (c) but whose actual spending is only in the 40th-60th percentile - these are "potential VIPs", (d) additionally flag any potential VIPs who have shown declining order frequency over the last 3 months. For each identified customer, show their current tier, potential tier, and the specific categories where engagement campaigns could maximize conversion.

-- Q11. Paytm's CFO is presenting to the Audit Committee about revenue quality. They need analysis of "revenue concentration risk" showing: (a) what percentage of revenue comes from customers who have been active less than 6 months ("new"), (b) among established customers (6+ months), what's the "revenue half-life" - the number of customers needed to reach 50% of established customer revenue, (c) identify any single customer or store that contributes more than 5% of monthly revenue, (d) compare these metrics across payment modes to identify dependency risks. The analysis must exclude test transactions (orders with exactly round amounts like 100, 500, 1000 that exceed 3 per customer).

-- Q12. Flipkart's Marketplace team is concerned about "seller gaming" - where sellers manipulate the platform through various schemes. Detect potential gaming by identifying: (a) sellers (suppliers) whose products have suspiciously high order volumes from very few customers (top 5 customers contribute >80% of orders), (b) products where the average time between order and 5-star review is less than 24 hours (if trackable) OR where 5-star review rate exceeds 95%, (c) sellers whose products are frequently ordered together by the same customers in patterns suggesting fake orders. For each flagged seller, show their gaming risk score, calculated as a composite of these three signals, and recommend an investigation priority (Critical/High/Medium).

-- Q13. Zomato's Competitive Intelligence team has a theory that certain competitors (identified by brand patterns in product names) are gaining market share through aggressive discounting. The analysis must: (a) identify product brands where the average discount percentage in order_items exceeds the category average discount, (b) among heavily discounting brands, calculate their market share change - comparing their percentage of category orders in the last 3 months vs previous 3 months, (c) correlate with whether these brands have premium products (above category average price) receiving heavier discounts than economy products, (d) exclude private label products (assuming certain brand patterns indicate this). Present a "competitive threat matrix" showing brand, discount intensity, market share change, and recommended counter-strategy.

-- Q14. BigBasket's Logistics Optimization team is tackling their "last mile" problem. They need to identify delivery patterns that predict customer dissatisfaction. The analysis includes: (a) calculating average delivery time (shipped to delivered) per courier and comparing to courier average, (b) identifying customers whose deliveries consistently exceed their city's average delivery time by more than 50%, (c) among these underserved customers, find those with high lifetime value (top 30%) who are at churn risk, (d) correlate delivery delays with specific product categories to identify if certain products cause delays. The final output should rank couriers by their "customer impact score" (number of high-value customers affected × average delay severity) and recommend route reassignments.

-- Q15. Myntra's Sustainability Officer needs to calculate the company's "fast fashion impact" for ESG reporting. This requires: (a) identifying "fast fashion" products - those with higher than average order frequency but shorter than average customer retention (customers don't reorder), (b) calculating the "waste coefficient" for each product - orders that resulted in returns as percentage of total, weighted by product price, (c) aggregating this by brand to create a "brand sustainability score", (d) identifying which customer segments (by age, city tier derived from customer data) drive fast fashion purchases. Present recommendations for which brands to feature less prominently and which customer segments to target with sustainability messaging.

-- Q16. PhonePe's Business Strategy team is evaluating expansion into a subscription model. They need to identify potential subscribers by finding: (a) customers with high purchase frequency (above 75th percentile) and low purchase variance (consistent order values within 20% of their mean), (b) among these, find customers whose purchase timing is predictable (similar gaps between orders, approximated by standard deviation of order gaps), (c) calculate what a subscription price should be set at to match their actual spending while offering them apparent savings, (d) segment these into "weekly", "bi-weekly", and "monthly" subscription tiers based on their order frequency. For each tier, calculate total addressable market, potential subscription revenue, and cannibalization risk.

-- Q17. Ola's Legal team is responding to a regulatory inquiry about labor practices. They need analysis showing: (a) employees whose effective hourly wage (salary / estimated hours, using attendance) falls below the region's average, (b) stores where this occurs for more than 30% of employees, (c) whether low-wage prevalence correlates with store performance (high-performing stores potentially overworking staff), (d) identify any patterns in department or role where wage issues concentrate. The analysis must calculate remediation cost - the total additional salary needed to bring every identified employee to at least the regional average.

-- Q18. Amazon's Advertising team needs to optimize their email campaign targeting. They want to identify: (a) customers whose email engagement (opens and clicks) exceeds the campaign average, (b) among engaged customers, find those who converted (ordered within 7 days of email) at rates above the campaign conversion rate, (c) analyze what these "super responders" have in common - their category preferences, order value range, and loyalty points status, (d) identify campaigns where targeting "super responder" profiles would have increased ROI, calculated as (additional conversions × average order value) / campaign budget. Present a "campaign optimization playbook" with specific targeting recommendations.

-- Q19. Swiggy's Investor Relations team is preparing materials showing "unit economics" improvement. They need analysis by customer cohort showing: (a) Customer Acquisition Cost proxy (marketing spend during first order month / new customers that month), (b) Customer Lifetime Value (total revenue from customer from first order onwards), (c) LTV/CAC ratio by cohort, (d) "payback period" - months until cumulative revenue from a cohort exceeds the acquisition cost. The tricky part: cohorts should be defined by first order month, and the analysis must compare these metrics across different "acquisition channels" (derived from whether the customer had email campaign association before first order).

-- Q20. IRCTC's Digital Transformation team is building a recommendation engine. They need to identify: (a) "affinity pairs" - products frequently bought together (appear in same order) with statistical significance (co-occurrence rate > 5% AND above random expectation), (b) "sequential pairs" - products where buying product A correlates with buying product B in a subsequent order, (c) "substitution pairs" - products where customers who buy product A rarely buy product B (negative correlation), (d) for each pair type, calculate confidence (how often the pattern holds) and lift (how much more likely than random). Present the top 20 pairs in each category with their commercial implication.

-- Q21. Reliance Retail's Format Strategy team is debating whether small format stores outperform large format. They need: (a) classify stores into size tiers based on employee count (proxy for size): Small (<10), Medium (10-25), Large (>25), (b) for each tier, calculate revenue per employee, profit margin (revenue - expenses / revenue), customer satisfaction (average review rating for orders from that store), (c) analyze if the pattern differs by region, (d) identify "outlier" stores that outperform their size tier significantly. The analysis must control for store age (older stores have advantage) by comparing within similar tenure bands.

-- Q22. Paytm's Product team is evaluating a "super app" strategy. They need to identify customers who are "ecosystem engaged" - using multiple Paytm services (proxied by using multiple payment modes and having activity across different store types). The analysis: (a) score customers by "ecosystem breadth" (number of distinct payment modes used × number of distinct store categories), (b) correlate ecosystem score with retention (continued ordering activity), (c) identify which combination of services predicts highest retention, (d) find customers with high breadth who have recently become less active - these are churn risks who might leave the ecosystem entirely. Calculate the revenue at risk from these potential churners.

-- Q23. Flipkart's Category Leadership team is analyzing "category killer" products - items so popular they drive traffic to the entire category. Identify: (a) products that appear in orders where customers also bought multiple other products from different categories (gateway products), (b) measure the "halo effect" - what's the incremental revenue from other categories in orders containing these gateway products vs orders without them, (c) identify which gateway products are also profitable on their own (price vs category average, return rate vs average), (d) recommend products that should receive promotional investment based on halo potential and own-margin contribution.

-- Q24. Zomato's Partner Success team is redesigning their restaurant commission structure. They need: (a) analysis of how current implied commission rates (calculated from order amounts vs what restaurants presumably receive) vary by restaurant performance tier, (b) identification of restaurants where order volume is high but average ticket size is low (potentially gaming minimum order requirements), (c) simulation of revenue impact if commission were tied to customer satisfaction scores (reviews), (d) identification of restaurants that would benefit vs suffer from the new model. Present a transition plan that protects total platform revenue while incentivizing quality.

-- Q25. BigBasket's Fresh Produce team is optimizing inventory for perishables. They need: (a) products where the time from inventory update to complete sellout (stock reaching zero) is shorter than the category average - fast movers, (b) among these, identify which have high variance in sell-through time (risky perishables), (c) calculate optimal order quantity as: average daily sales × target days of supply, but adjust for variance, (d) flag products where current inventory significantly exceeds optimal quantity - potential waste. The analysis must separately handle products with promotions active (promo periods) as they have different velocity patterns.

-- Q26. Myntra's FP&A team is building a revenue forecasting model. They need historical patterns showing: (a) seasonality coefficients by category (how does each category's monthly revenue compare to its annual average), (b) trend components (is each category growing, declining, or flat based on year-over-year comparison), (c) correlation between categories (when category A has a good month, does category B also), (d) impact of marketing spend on revenue with appropriate lag (campaign effects might be delayed). Present a forecast framework showing predicted revenue by category for the next quarter based on these patterns.

-- Q27. PhonePe's Trust & Safety team is building fraud rules. They need to identify: (a) "velocity anomalies" - customers whose order rate in any week exceeds 3× their historical weekly average, (b) "amount anomalies" - orders where the amount exceeds the customer's usual range by more than 2 standard deviations, (c) "pattern anomalies" - sudden changes in payment mode, store preference, or product categories, (d) combine these into a "fraud probability score" weighted by historical fraud patterns in similar anomalies. For scored transactions, recommend threshold for automatic review vs automatic block.

-- Q28. Ola's Fleet Procurement team is negotiating vehicle purchases. They need analysis of: (a) optimal store-to-employee ratio based on revenue optimization (find the ratio where revenue per employee is maximized), (b) stores that are over-staffed vs under-staffed relative to this optimal, (c) forecasted hiring needs based on revenue growth trajectory by region, (d) locations where new stores would be profitable based on existing customer density without nearby stores. Present procurement recommendations with headcount and store opening timelines.

-- Q29. Amazon's Vendor Management team is implementing a "Vendor Scorecard" system. Calculate for each supplier: (a) Quality Score: (1 - return rate) weighted by revenue contribution, (b) Delivery Score: percentage of orders shipped within expected timeframe, (c) Price Competitiveness: how supplier's average prices compare to category averages, (d) Growth Contribution: supplier's share of revenue change compared to same period last year. Create composite scores and rank suppliers into tiers (Platinum, Gold, Silver, Bronze) where each tier has different payment terms implications.

-- Q30. Swiggy's Cloud Kitchen Investment team is selecting locations for new ghost kitchens. They need: (a) demand hotspots - cities/areas where delivery orders per capita exceed the national average, (b) supply gaps - same areas where current restaurant capacity (orders handled per store) is at or above threshold, (c) competitive intensity analysis - areas where no single restaurant dominates (none have >15% of orders), (d) unit economics potential - calculate projected revenue based on area's average order value and frequency, vs estimated costs. Rank locations by investment attractiveness score.

-- Q31. IRCTC's Customer Experience team is implementing "proactive service recovery" - identifying customers likely to complain before they do. Find customers who: (a) have experienced service failures (late deliveries, returns, order cancellations) at rates above their cohort average, (b) whose sentiment might be declining (decreasing order values, longer gaps between orders), (c) but who are valuable enough to warrant recovery investment (lifetime value in top 40%), (d) predict which specific service failure type is most likely bothering them based on their history. Recommend personalized recovery actions for top 100 at-risk valuable customers.

-- Q32. Reliance Digital's Merchandise Planning team is optimizing assortment by store. They need: (a) identify products that sell well nationally but poorly at specific stores (local assortment opportunities), (b) identify products that sell well only at specific stores (potential for broader rollout), (c) for underperforming product-store combinations, analyze if it's a demand issue (low category demand at store) or a product issue (other products in same category sell well), (d) recommend assortment changes: products to add, products to remove, products to promote differently by store.

-- Q33. Paytm's Business Intelligence team is building a "merchant health" monitoring system. For each store, calculate: (a) Revenue Trajectory (3-month trend: growing/declining/stable), (b) Customer Diversity (how concentrated is revenue among top customers), (c) Product Mix Health (variety of products being ordered vs store's available catalog), (d) Payment Risk (percentage of orders with payment delays or failures). Create a composite "merchant health score" and identify stores scoring below 50th percentile on multiple dimensions - candidates for relationship manager intervention.

-- Q34. Flipkart's Search & Discovery team is improving product rankings. They need: (a) products with high "discovery rate" (orders where the product wasn't the primary category searched - indicated by orders with diverse category mix), (b) products with high "conversion rate" (orders / times appearing in orders with other products as proxies for impressions), (c) products where discovery rate is high but conversion is low (visibility without purchase - potential pricing or description issue), (d) correlation between product attributes (price, reviews, brand) and discovery/conversion metrics. Recommend ranking algorithm weights based on these insights.

-- Q35. Zomato's Premium Program team is launching "Zomato Select" with exclusive restaurants. They need: (a) restaurants (stores) whose average order value is in top 20% but customer base is relatively small (exclusive, premium positioning), (b) among these, identify which have exceptional repeat customer rates (above average), (c) model the revenue impact of making these exclusive - estimate lost orders from non-premium customers vs increased orders from premium members attracted to exclusivity, (d) identify customer segments who would value exclusivity (based on their current premium restaurant ordering patterns).

-- Q36. BigBasket's Data Science team is validating their churn prediction model. They need historical analysis showing: (a) which customer attributes at time T predicted churn by time T+90days, (b) calculate prediction accuracy: of customers predicted to churn (define criteria: decreasing order frequency, decreased spend, increased gaps), what percentage actually churned (no orders in next 90 days), (c) calculate economic impact: revenue lost from correctly predicted churners vs cost of retention attempts, (d) identify "false positives" - customers predicted to churn who didn't - what made them different. Present model validation report.

-- Q37. Myntra's Brand Strategy team is evaluating private label expansion opportunities. They need: (a) categories where private label products don't exist but should (high margin category, fragmented brand landscape), (b) price points where there's unmet demand (order distribution by price shows gaps not covered by existing products), (c) categories where competitor private labels (if identifiable by naming patterns) are succeeding, (d) customer segments who are "private label friendly" (price-sensitive, low brand loyalty indicated by diverse brand purchases). Recommend 5 categories with business case for each.

-- Q38. PhonePe's Growth team is optimizing user activation. They need to identify: (a) customers who completed one transaction but never returned ("one and done"), (b) analyze what these customers' first transaction looked like (amount, payment mode, product category) vs customers who became active, (c) identify specific "activation triggers" - second transactions that predict long-term retention, (d) calculate the "activation opportunity" - revenue potential if one-and-done customers had been converted at average rates. Recommend changes to first-time user experience.

-- Q39. Ola's Risk team is modeling loan eligibility for employee advances. They need: (a) employees whose salary history shows stable or growing trajectory (good repayment capacity), (b) attendance patterns indicating reliability (high attendance percentage), (c) store performance correlation (employees at well-performing stores may have more stable employment), (d) calculate maximum safe loan amount as: (monthly salary × stability score × tenure factor). Present eligibility tiers and recommended interest rates for each tier.

-- Q40. Amazon's Last-Mile Innovation team is evaluating delivery locker placement. They need: (a) customer clusters - geographic concentrations of customers (by city, then drill down by customer patterns), (b) among clusters, identify "delivery-frustrated" clusters where delivery times exceed average or where multiple delivery attempts are common (if inferable), (c) estimate locker demand based on order volumes and customer density, (d) model cost savings from locker delivery vs traditional delivery (reduced failed attempts, bulk delivery efficiency). Rank locations by ROI potential.

-- Q41. Swiggy's Kitchen Operations team is optimizing menu complexity. They need: (a) stores where order preparation complexity (unique products per order) has increased but customer satisfaction has decreased, (b) products that create "bottleneck" patterns - when ordered, they delay other items (indicated by longer overall delivery times), (c) revenue contribution of complex products vs simple high-volume products, (d) recommendations for menu simplification: products to retire (low volume, high complexity) vs products to keep (high margin or gateway products).

-- Q42. IRCTC's Dynamic Yield team is implementing demand-based pricing. They need: (a) historical price-demand relationships by product (how did demand change when prices changed), (b) identification of "price anchors" - customers who only buy within certain price ranges, (c) optimal price points that maximize revenue (price × quantity), (d) constraints: cannot price above certain thresholds for essential products. Present pricing recommendations with revenue impact simulation.

-- Q43. Reliance Retail's Loss Prevention team is detecting internal shrinkage (employee theft patterns). They need: (a) stores where inventory discrepancies (stock vs sold vs returned) exceed threshold, (b) correlation between discrepancies and specific employees (based on who was working at the store during issue periods - attendance records), (c) products most vulnerable to shrinkage (high value, small size - approximate by category and price), (d) pattern analysis: do discrepancies cluster around specific times, days, or events. Present investigation priorities with sensitivity to false accusations.

-- Q44. Paytm's Credit team is building risk models for merchant cash advances. They need: (a) store revenue consistency (monthly variance - lower is better), (b) customer diversification (concentration risk if few customers drive revenue), (c) seasonal adjustment (stores with high seasonality need different terms), (d) growth trajectory (growing merchants are better risks). Create risk tiers and recommend advance amounts as percentage of monthly revenue based on tier.

-- Q45. Flipkart's Seller Education team is identifying struggling sellers who need support. They need: (a) sellers (suppliers) whose sales have declined month-over-month for 2+ consecutive months, (b) among struggling sellers, identify if the issue is demand (category declining) or seller-specific (seller underperforming category), (c) sellers with potential - high-quality products (good reviews) but poor visibility (low order volumes), (d) successful seller benchmarks - what do top-performing sellers in same category do differently. Create intervention playbook with seller-specific recommendations.

-- Q46. Zomato's Financial Planning team is creating a unit economics model. They need: (a) fully-loaded cost per order (allocate all marketing, operational costs across orders), (b) revenue per order (order amount minus discounts minus partner payouts approximated), (c) breakeven analysis: how many orders does a customer need to place before they're profitable, (d) customer cohort profitability: which cohorts reach profitability fastest. Present model with sensitivity analysis on key assumptions.

-- Q47. BigBasket's Operations Research team is optimizing delivery routing. They need: (a) customer ordering patterns: when do different customer segments typically order (day of week, time of month - approximated), (b) geographic clustering: customers who could be efficiently served together, (c) vehicle capacity utilization: how many orders typically go in each delivery run (average items per order × orders per route), (d) optimization opportunities: underutilized routes that could absorb more orders. Present recommendations for route redesign.

-- Q48. Myntra's Personalization team is building style profiles. They need: (a) implicit style preferences: what patterns exist in each customer's order history (brands, price ranges, categories), (b) style tribes: clusters of customers with similar style profiles, (c) style evolution: how do preferences change over time for different customer segments, (d) style influencers: customers whose purchases predict broader trends. Create customer style profiles for personalized recommendations.

-- Q49. PhonePe's Product Management team is prioritizing feature development. They need: (a) user journey analysis: common transaction patterns (what do users do before and after each transaction type), (b) friction points: where do users abandon (orders without payments, incomplete transactions), (c) feature adoption correlation: which features used together indicate power users, (d) feature opportunity sizing: estimate impact of improving each identified friction point based on affected order volume. Present prioritized feature roadmap.

-- Q50. Ola's Market Expansion team is evaluating new city entry. They need: (a) existing customer spillover: do they have customers in target city who currently can't be served well (orders to stores far from their city), (b) demand indicators: based on comparable city patterns, what order volumes could they expect, (c) competitive intensity proxy: how concentrated are orders among existing stores in similar city types, (d) infrastructure requirements: staff, store, inventory needs based on projected demand. Create city entry playbook with go/no-go recommendations.

-- Q51. Amazon's Retail Media team is optimizing ad placements. For products with advertising (assume campaigns linked to products): (a) calculate ROAS (return on ad spend): incremental orders during campaign vs ad cost, (b) identify products where organic sales (non-campaign period) were cannibalized by ads (no true incrementality), (c) optimal ad budget allocation across products based on marginal return curves, (d) seasonality interaction: when do ads work best for each product category. Present advertising optimization recommendations.

-- Q52. Swiggy's Partner Relations team is redesigning restaurant tiers. They need: (a) current tier implications: how do order volumes, average values, and customer satisfaction differ by restaurant tier (based on order patterns), (b) tier mobility: which restaurants have moved up/down based on performance, (c) tier fairness analysis: are there restaurants that should be in different tiers based on objective metrics, (d) tier benefit design: what exclusive benefits would incentivize restaurants to improve. Present new tier structure with transition plan.

-- Q53. IRCTC's Revenue Assurance team is detecting revenue leakage. They need: (a) orders with pricing inconsistencies (order_item unit prices significantly different from product catalog prices without promotion justification), (b) discount abuse patterns: customers or stores with abnormally high discount rates, (c) returns without refund processing (returns recorded but no refund amount), (d) quantification of leakage: total revenue impacted by each leakage type. Present audit findings with remediation recommendations.

-- Q54. Reliance Digital's Store Operations team is benchmarking store performance fairly. They need: (a) adjust performance metrics for factors outside store control (location demographics, store age, competitive intensity), (b) calculate "expected performance" based on these factors for each store, (c) identify outperformers and underperformers relative to expectations, (d) diagnose underperformance causes: is it traffic (low orders), conversion (low items per order), or ticket size (low revenue per item). Present fair performance rankings with improvement plans.

-- Q55. Paytm's Business Development team is identifying partnership opportunities. They need: (a) product categories where customer demand exists but supply is limited (high search-to-order ratio proxy: high customer count but low orders in category), (b) stores that could expand into adjacent categories based on their customer base preferences, (c) category + location combinations with unmet demand, (d) potential partner profiles: what characteristics should ideal category partners have. Present partnership opportunity pipeline.

-- Q56. Flipkart's Warehouse Operations team is optimizing pick-pack-ship. They need: (a) products frequently ordered together that should be stored together (co-location efficiency), (b) products with different velocity tiers (fast vs slow movers) for storage zone planning, (c) seasonal shifts in velocity that require dynamic slotting, (d) bundling opportunities: product combinations that could be pre-packaged based on order patterns. Present warehouse optimization recommendations with efficiency impact estimates.

-- Q57. Zomato's Market Research team is analyzing competitive dynamics. They need: (a) market share trends by category: which brands are gaining vs losing share over time, (b) price war detection: categories where average prices are declining while volumes increase, (c) quality competition: categories where average ratings are increasing (quality arms race), (d) differentiation analysis: what distinguishes leading brands from followers in each category. Present competitive landscape report.

-- Q58. BigBasket's Category Management team is rationalizing SKUs. They need: (a) products contributing minimal revenue but significant operational complexity (long-tail elimination candidates), (b) products with high substitutability (customers who buy Product A rarely buy Product B and vice versa - can eliminate one), (c) assortment gaps: product attributes not covered by current selection but showing in order patterns from adjacent categories, (d) rationalization impact: estimate revenue at risk from eliminating long-tail products vs operational savings. Present SKU rationalization recommendations.

-- Q59. Myntra's Returns Management team is attacking returns cost. They need: (a) predictive signals for returns: customer, product, and order characteristics that predict high return likelihood, (b) "serial returners" identification: customers with return rates significantly above average, (c) product fit issues: products where returns cluster around specific reasons (size, quality, expectation mismatch), (d) cost of returns by category including logistics, processing, and inventory impact. Present returns reduction strategy.

-- Q60. PhonePe's Compliance team is preparing regulatory reports. They need: (a) transaction volume and value summaries by geography and time period, (b) large transaction patterns that may require reporting, (c) customer concentration analysis: dependency on any customer segment, (d) geographic spread of business: does activity concentrate in specific areas. Present compliance dashboard framework.

-- Q61. Ola's Training team is identifying skill gaps. They need: (a) employees whose performance metrics (orders handled, customer satisfaction at their store) are below peer average, (b) pattern analysis: do skill gaps cluster by role, department, or tenure, (c) training ROI: for employees who received training (approximated by tenure milestones), did performance improve, (d) training priority: rank skill gaps by business impact. Present training needs assessment.

-- Q62. Amazon's Sustainability team is calculating carbon footprint. They need: (a) shipment distance proxies based on store and customer locations, (b) order consolidation efficiency: how many items ship together vs separately, (c) return miles: logistics cost of returns processing, (d) packaging efficiency proxy: ratio of items to orders (fewer items per order = more packaging). Present sustainability metrics with reduction opportunities.

-- Q63. Swiggy's Menu Analytics team is identifying hero items. They need: (a) products that drive first orders for customers (gateway products), (b) products that are most frequently the highest-value item in orders (anchor products), (c) products with exceptional repeat rates (customers order multiple times), (d) profitability analysis: which hero items are also high margin. Present hero product strategy.

-- Q64. IRCTC's Loyalty Program team is redesigning rewards. They need: (a) current redemption patterns: how are loyalty points being used, (b) point accumulation patterns by customer segment, (c) loyalty program ROI: do high-point customers spend more than the cost of points, (d) optimal point valuation: what point value maximizes engagement while protecting economics. Present loyalty program redesign.

-- Q65. Reliance Retail's Space Planning team is optimizing floor layouts. They need: (a) category affinity analysis: which categories are often bought together (should be adjacent), (b) category traffic patterns: which categories draw customers (should be distributed for traffic flow), (c) category profitability: margin contribution by category (prime space for high margin), (d) impulse vs destination analysis: which categories are planned purchases vs impulse (placement strategy). Present space planning principles.

-- Q66. Paytm's Growth Marketing team is optimizing referral programs. They need: (a) referral network analysis: customers who likely referred others (joined around same time with similar first purchases), (b) referral quality: do referred customers have better or worse lifetime value, (c) viral coefficient estimation: how many new customers does each referrer bring on average, (d) optimal referral incentive: what reward level maximizes ROI of referral program. Present referral optimization recommendations.

-- Q67. Flipkart's Seller Acquisition team is identifying potential new sellers. They need: (a) categories with supply constraints (high demand relative to product availability), (b) supplier profile analysis: what characteristics distinguish successful suppliers, (c) geographic gaps: regions with customer demand but limited seller presence, (d) seller economics modeling: what volume and margins do sellers need for viability. Present seller recruitment targeting strategy.

-- Q68. Zomato's Hyperlocal Strategy team is optimizing delivery zones. They need: (a) delivery efficiency by zone: average delivery time, success rate, (b) demand density by zone: orders per square kilometer proxy, (c) capacity matching: are zones balanced in terms of demand vs delivery capacity, (d) zone boundary optimization: customers at zone edges who might be better served by adjacent zones. Present delivery zone redesign.

-- Q69. BigBasket's Freshness team is minimizing waste. They need: (a) products with short shelf life and high inventory days (waste risk), (b) demand forecasting accuracy: how often does actual demand match expected (inventory × turnover), (c) markdown effectiveness: do discounts accelerate sellthrough enough, (d) supplier coordination: does supplier delivery schedule match demand patterns. Present waste reduction strategy.

-- Q70. Myntra's Sizing team is improving size recommendations. They need: (a) return patterns by size: which sizes have highest return rates, (b) size substitution patterns: when customers return for size reason, what size do they exchange for, (c) brand sizing consistency: do certain brands have different fit than their labeled size implies, (d) customer size profiles: can purchase history predict sizing preferences. Present sizing optimization recommendations.

-- Q71. PhonePe's International Expansion team is evaluating market entry. They need: (a) customer behavior portability: how similar are order patterns to comparable markets (benchmark countries if available), (b) payment behavior analysis: does transaction structure suggest readiness for digital payments, (c) regulatory complexity: volume of high-value transactions requiring special handling, (d) partnership requirements: category gaps that would need local partners. Present market entry assessment framework.

-- Q72. Ola's Customer Feedback team is implementing voice of customer. They need: (a) satisfaction drivers: what order characteristics correlate with high reviews, (b) dissatisfaction patterns: what happens before low reviews, (c) silent churners vs vocal complainers: do customers who complain actually churn less, (d) recovery effectiveness: do customers who experienced problems but got resolution become more loyal. Present customer feedback strategy.

-- Q73. Amazon's Inventory Finance team is optimizing working capital. They need: (a) inventory investment by category: stock value tied up, (b) inventory turnover: how fast does investment convert to revenue, (c) payment terms optimization: cash conversion cycle by supplier, (d) seasonal working capital needs: inventory build requirements by period. Present working capital optimization recommendations.

-- Q74. Swiggy's New Vertical team is evaluating grocery delivery. They need: (a) existing customer affinity for grocery: do current customers show grocery-like purchase patterns (frequent, small baskets of essentials), (b) geographic suitability: areas with high customer density suitable for quick commerce, (c) competitive intensity: existing players in grocery delivery (based on category patterns), (d) unit economics projection: based on order patterns, what volumes are needed for profitability. Present grocery vertical business case.

-- Q75. IRCTC's Ancillary Revenue team is maximizing add-on sales. They need: (a) main purchase patterns: what are customers primarily buying, (b) add-on affinity: which products are commonly added to main purchases, (c) upsell success rates: when add-ons are suggested (during promotions), what's conversion, (d) optimal timing: when in the customer journey are add-ons most effective. Present add-on revenue strategy.

-- Q76. Reliance Retail's Franchise team is supporting franchisee success. They need: (a) franchisee performance benchmarks: how do franchisee stores compare to corporate stores, (b) support needs identification: which franchisees are struggling and why, (c) best practice transfer: what do top franchisees do differently, (d) territory optimization: are franchise territories balanced for opportunity. Present franchisee support recommendations.

-- Q77. Paytm's Platform Security team is detecting account takeover. They need: (a) behavioral anomalies: sudden changes in ordering patterns suggesting compromised accounts, (b) device/location signals: orders from unusual circumstances (different cities in short timeframe), (c) payment method changes: suspicious updates to payment preferences, (d) impact quantification: orders affected and revenue at risk. Present account security enhancement recommendations.

-- Q78. Flipkart's Fulfillment Network team is optimizing warehouse placement. They need: (a) demand centers: where does order volume concentrate, (b) shipping distance analysis: average distance from current warehouses to customers, (c) network simulation: how would adding/moving warehouses affect delivery times, (d) cost-benefit: infrastructure investment vs shipping cost savings. Present network optimization recommendations.

-- Q79. Zomato's Restaurant Intelligence team is helping partners grow. They need: (a) restaurant potential assessment: restaurants with good product quality but low visibility, (b) menu optimization: items that should be promoted vs deprecated based on performance, (c) competitive positioning: how restaurants compare to nearby alternatives, (d) growth playbook: specific actions for restaurants to increase order volume. Present restaurant growth recommendations.

-- Q80. BigBasket's Customer Insights team is understanding shopping missions. They need: (a) basket archetypes: common combinations of products that represent shopping missions, (b) mission timing: when do different missions happen (weekly stock-up vs immediate need), (c) mission value: which missions are most valuable and loyal, (d) mission completion: are customers getting everything they need in one trip. Present shopping mission framework.

-- Q81. Myntra's Trend Forecasting team is predicting fashion trends. They need: (a) emerging signals: products with accelerating growth rates, (b) trend diffusion: how do trends spread from early adopters to mainstream, (c) trend lifespan: how long do trends last before decline, (d) trend prediction model: what early signals predict successful trends. Present trend forecasting methodology.

-- Q82. PhonePe's Financial Inclusion team is expanding access. They need: (a) underserved segments: customer groups with lower transaction frequency or value, (b) access barriers: what might be preventing fuller participation (transaction patterns), (c) product gaps: financial services not being addressed, (d) inclusion opportunity sizing: potential revenue from serving underserved segments. Present financial inclusion strategy.

-- Q83. Ola's Route Optimization team is improving delivery efficiency. They need: (a) current route analysis: delivery time by route type, (b) bottleneck identification: which legs of journeys are slowest, (c) batching opportunities: orders that could be combined efficiently, (d) dynamic routing needs: how do optimal routes change by time of day. Present delivery optimization recommendations.

-- Q84. Amazon's Advertising Attribution team is measuring ad effectiveness. They need: (a) direct attribution: orders clearly linked to campaigns, (b) view-through attribution: orders after campaign exposure but not click, (c) incrementality analysis: would these orders have happened without ads, (d) attribution model comparison: how do different models change credit allocation. Present advertising attribution framework.

-- Q85. Swiggy's Customer Value team is optimizing customer investment. They need: (a) customer value tiers: segment customers by predicted lifetime value, (b) investment allocation: how much to spend acquiring/retaining each tier, (c) value migration: track customers moving between tiers, (d) intervention triggers: signals that indicate need for retention action. Present customer value management framework.

-- Q86. IRCTC's Pricing Analytics team is implementing dynamic pricing. They need: (a) demand patterns: how does demand vary by time, day, season, (b) price sensitivity: how do different customer segments respond to prices, (c) competitor pricing: what's the competitive pricing context (if available through patterns), (d) optimal pricing rules: when to raise vs lower prices. Present dynamic pricing framework.

-- Q87. Reliance Retail's Customer Data Platform team is building unified profiles. They need: (a) identity resolution: linking same customers across different identifiers, (b) profile enrichment: what attributes can be inferred from behavior, (c) profile completeness: what's known vs unknown about each customer, (d) profile activation: how to use profiles for personalization. Present customer data strategy.

-- Q88. Paytm's Merchant Services team is expanding product offerings. They need: (a) merchant needs assessment: what services do merchants need based on their patterns, (b) service adoption: which merchants use which services, (c) cross-sell opportunity: merchants likely to adopt additional services, (d) service bundling: which services are commonly used together. Present merchant services growth strategy.

-- Q89. Flipkart's Assortment Intelligence team is competing with specialists. They need: (a) category specialists: categories where specialists likely outperform, (b) competitive gap analysis: where is selection or pricing uncompetitive, (c) assortment priorities: which gaps to close first based on demand, (d) long-tail strategy: when is breadth vs depth more valuable. Present competitive assortment strategy.

-- Q90. Zomato's Cloud Kitchen team is optimizing kitchen operations. They need: (a) menu rationalization: items that are operationally complex but low volume, (b) kitchen capacity: order volume vs estimated preparation capacity, (c) time-based demand: how does demand vary through the day, (d) prep scheduling: when should ingredients be prepped based on demand patterns. Present kitchen optimization recommendations.

-- Q91. BigBasket's Supply Chain Finance team is optimizing supplier terms. They need: (a) supplier importance: ranking by revenue contribution, (b) supplier reliability: delivery and quality performance, (c) payment terms analysis: current days payable by supplier tier, (d) cash flow optimization: terms changes to improve working capital. Present supplier terms optimization.

-- Q92. Myntra's Visual Merchandising team is optimizing product presentation. They need: (a) image performance: which product presentations drive better conversion (based on category patterns), (b) catalog completeness: products missing key attributes or images, (c) content quality: products with performance below category average potentially due to content, (d) content investment priority: where will content improvement have most impact. Present visual merchandising recommendations.

-- Q93. PhonePe's Partnerships team is structuring revenue sharing. They need: (a) partner contribution analysis: what value does each partner bring, (b) economics by partner type: which partnerships are most profitable, (c) fair value allocation: how should revenue be split based on contribution, (d) partnership optimization: which partnerships to grow, maintain, or exit. Present partnership economics framework.

-- Q94. Ola's Capacity Planning team is matching supply with demand. They need: (a) demand forecasting: predict order volumes by location and time, (b) supply assessment: current capacity by location, (c) gap analysis: where is capacity insufficient, (d) capacity addition plan: where and when to add capacity. Present capacity planning recommendations.

-- Q95. Amazon's Subscribe & Save team is optimizing subscription pricing. They need: (a) subscription potential: products with regular repurchase patterns, (b) subscription economics: discount vs retention value, (c) churn prediction: what signals indicate subscription cancellation risk, (d) subscription tier design: how to structure subscription options. Present subscription optimization strategy.

-- Q96. Swiggy's Advertising team is launching restaurant ads. They need: (a) advertiser potential: restaurants that would benefit from advertising, (b) ad inventory: where can ads be placed effectively, (c) pricing model: how to charge for ads based on value delivered, (d) performance measurement: how to demonstrate ad ROI to restaurants. Present advertising product design.

-- Q97. IRCTC's Experience Design team is reducing friction. They need: (a) drop-off analysis: where in the order process do customers abandon, (b) friction correlation: what factors correlate with abandonment, (c) improvement prioritization: which friction points have biggest impact on revenue, (d) success metrics: how to measure friction reduction effectiveness. Present friction reduction recommendations.

-- Q98. Reliance Retail's Omnichannel team is integrating online-offline. They need: (a) cross-channel behavior: customers who interact with both channels, (b) channel preferences: which customers prefer which channels for what, (c) BOPIS analysis: buy-online-pickup-in-store patterns, (d) unified experience: where are channel handoffs creating friction. Present omnichannel strategy.

-- Q99. Paytm's SuperApp team is designing unified experience. They need: (a) service utilization: which services do customers use, (b) service synergies: which services are used together, (c) journey mapping: how do customers move between services, (d) unified home screen: what should be prominent for different user types. Present superapp experience design.

-- Q100. Flipkart's Long-term Strategy team is planning 5-year roadmap. They need: (a) market evolution: how is customer behavior changing over time, (b) category lifecycle: which categories are growing vs maturing, (c) customer cohort analysis: are newer customers different from older ones, (d) competitive evolution: how is competitive intensity changing. Present strategic analysis with long-term implications.

-- ============================================
-- END OF DAY 11 CRAZY HARD QUESTIONS
-- ============================================
